// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the UI needs to say about the output device (FR-014).
 */
export type DeviceNotice = { 
/**
 * `ok`, `recovering` or `failed`.
 */
state: string, 
/**
 * True when this is a recovery rather than the first device opening, so
 * the UI can say "back" instead of announcing something that never broke.
 */
recovered: boolean, };

/**
 * What `play_pattern` reports back.
 */
export type PlaybackStarted = { 
/**
 * Notes in lanes this kit has no pad for. Zero on the shipped kit; a
 * number here means part of the pattern is inaudible.
 */
unplacedNotes: number, voices: number, };

/**
 * What the frontend draws the playhead from.
 */
export type Playhead = { playing: boolean, 
/**
 * Position through the loop, 0–1. Absent a loop, 0.
 */
position: number, 
/**
 * The same position in beats, for a bar counter.
 */
beat: number, };
