// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Performance marking. Carries intent the raw velocity cannot: a ghost note
 * and a quiet main hit are the same number but not the same musical event.
 */
export type Articulation = "ghost" | "accent" | "legato" | "staccato" | "roll";

/**
 * A model the app could not use, in the form the UI reports it (FR-001).
 *
 * A list rather than a count, because a badge saying "3" tells a user nothing
 * they can act on — the file and the reason do.
 */
export type DatasetProblem = { 
/**
 * The file it came from, or the model id when the failure was in the merge.
 */
source: string, message: string, };

/**
 * How far generated notes are pulled off the grid, and how much velocities
 * vary. Jitter is per lane because a hat and a kick do not breathe alike.
 */
export type Humanize = { 
/**
 * `1.0` snaps hard to the grid; `0.0` leaves the raw performance offset.
 */
quantizeStrength: number, 
/**
 * Fractional velocity spread, e.g. `0.12` = ±12%.
 */
velocityVar: number, 
/**
 * Per-lane timing jitter in milliseconds.
 */
timingJitterMs?: { [key in Lane]?: number }, };

/**
 * A voice within a pattern. Drum parts use several; melodic parts use one.
 */
export type Lane = "kick" | "subKick" | "snare" | "offSnare" | "ghostSnare" | "clap" | "closedHat" | "openHat" | "pedalHat" | "ride" | "rideBell" | "crash" | "tom" | "tomHigh" | "tomLow" | "rim" | "snap" | "perc" | "perc2" | "shaker" | "tambourine" | "cowbell" | "clave" | "conga" | "bongo" | "timbale" | "triangle" | "woodblock" | "riser" | "impact" | "reverse" | "sub" | "subLow" | "melody" | "counter" | "bass" | "chords";

export type LaneTrack = { lane: Lane, notes: Array<Note>, };

export type ModelType = "artist" | "producer" | "genre";

/**
 * A single note event. Ticks are absolute from the start of the pattern.
 */
export type Note = { startTick: number, lenTicks: number, 
/**
 * MIDI note number, 0–127.
 */
pitch: number, 
/**
 * MIDI velocity, 1–127.
 */
vel: number, 
/**
 * What the model itself wrote here, before [`crate::humanize`] spread it
 * (TASK-041V).
 *
 * ⛔ **The velocity lane's "reset" needs this and cannot recompute it.**
 * Resetting a cap has to put back the value that note's own lane tier
 * asked for — a ghost note's 40, an accent's 120 — and by the time anyone
 * can see the lane, `vary` has already spread it by a random factor that
 * is not invertible. Resetting to a flat 100 instead would quietly delete
 * the accent pattern that is the difference between a played pattern and a
 * programmed one, using the control whose whole promise is "put it back".
 *
 * `None` on a note nobody generated — one the producer drew — where there
 * is no model opinion to return to.
 */
modelVel?: number | null, 
/**
 * 808 slide target. The note glides to this pitch; the writer emits the
 * overlap convention the sampler reads as portamento.
 */
slideToPitch?: number | null, articulation?: Articulation | null, 
/**
 * Play this one note's sample **backwards** (2026-08-11).
 *
 * ⛔⛔ **Mike:** *"if you have a drum pad or something playing forward in
 * the pad, but you want it to play backwards in the drum pattern, you should
 * be able to switch it … select the note and press like 'Ctrl+R' or
 * 'Command+R' on macOS to reverse the note just for that single note being
 * played. i think this would be a VERY USABLE AND COOL FEATURE to have."*
 *
 * ⛔ **Per NOTE, and deliberately not the same thing as a reversed
 * one-shot.** A pad can be *assigned* a reversed sample (`Ctrl`+← in the
 * browser, stored in `PluginSession::one_shots_reversed`), and that flips the
 * buffer once at load time because it never changes. This is the opposite
 * case: the same pad sounding forwards on one hit and backwards on the next
 * inside one pattern, so it can only be read per voice, at trigger time.
 *
 * ⛔ **A `.mid` cannot carry it.** There is no SMF representation of "play
 * this sample backwards", so a dragged or exported MIDI clip loses it and
 * only the audio keeps it. That is a real limit of the format rather than
 * something to work around, and it is written here so the next reader does
 * not go looking for the encoding.
 *
 * ⚠ `#[serde(default)]` and skipped when false, so every pattern already on
 * disk — and every golden snapshot — deserializes unchanged and gains
 * nothing in its serialized form.
 */
reversed?: boolean, };

/**
 * The five generated parts. `Drums` covers the whole kit including the 808,
 * which doubles as the bassline lane in trap-family styles.
 */
export type Part = "drums" | "melody" | "counter" | "bass" | "chords";

/**
 * One generated clip for one part.
 */
export type Pattern = { id: string, part: Part, 
/**
 * The style model this came from — an artist or a genre archetype.
 */
artistId: string, 
/**
 * **The take's seed.** What rerolls on every press of Generate.
 */
seed: string, 
/**
 * **The record's seed** — the harmonic plan every part is written against
 * (TASK-141).
 *
 * ⛔ **The page has to hand this back on the next Generate**, or the five
 * parts stop agreeing. That is the whole mechanism: the take rerolls, the
 * record is carried. A caller that ignores it gets the pre-TASK-141
 * behaviour, where Generate on Drums and then Generate on Melody drew two
 * unrelated seeds and wrote the melody against a harmony the chords tab
 * had never seen.
 *
 * ⚠ Defaults to [`Self::seed`] when absent, so a project saved before this
 * existed reopens as one seed for everything — which is exactly what it
 * meant.
 */
songSeed: string, bars: number, bpm: number, timeSigNum: number, timeSigDen: number, 
/**
 * Pitch class of the key root, 0 = C.
 */
keyRoot: number, scale: Scale, lanes: Array<LaneTrack>, ppq: number, 
/**
 * The mode this was generated in, when the model offers any (TASK-040V).
 *
 * Carried on the pattern because a mood picked by the seed is otherwise
 * invisible: "Any" has to be able to say *which* one it landed on, for the
 * same reason the seed box echoes back the seed it used. `None` means the
 * model offers no modes, not that one was declined.
 */
mood?: string | null, 
/**
 * What the transport repeats, in ticks (TASK-041E).
 *
 * `None` is the whole clip, which is what every pattern is until someone
 * drags a brace. Carried on the pattern rather than held beside it because
 * it is a property of the clip: it saves with the project, travels with a
 * preset, and an edited clip that forgot its own loop on reload would be
 * the kind of quiet loss nobody attributes to the right feature.
 */
loopRegion?: Region | null, 
/**
 * The clip's own start and end, independent of the loop.
 */
clipRegion?: Region | null, };

export type PatternRef = { patternId: string, 
/**
 * How many bars of the clip this row plays before it repeats (TASK-142).
 *
 * ⛔ **This is what "resize a clip" means in an arrangement, and it had to
 * live on the *reference* rather than on the pattern.** Sections of the
 * same kind share one [`Pattern`] — that is [`crate::arrange`]'s second
 * stated decision, and the whole reason this is an id — so shortening the
 * pattern would shorten every verse in the song at once. On the reference
 * it is what a producer means: *this* row, in *this* section, loops on two
 * bars instead of four.
 *
 * ⚠ **`None` is the pattern's own length**, which is what every song built
 * before this field meant and what a fresh arrangement still means. It is
 * not "zero" and not "one bar": a default here would silently retile every
 * saved project on the first reopen.
 *
 * ⛔ Read only through [`SectionTiling::of`], which is the one place the
 * exporter and the transport both go — see that type's own note on why
 * two walks over these fields is a bug this project has already shipped
 * twice.
 */
bars?: number | null, };

/**
 * A span of a clip, in absolute ticks (TASK-041E).
 *
 * Used for both the loop brace and the clip's own start and end, which are
 * deliberately two different things: a producer loops bar 2 of a four-bar idea
 * to work on it, and trims the clip to bars 1–3 to keep it. One field for both
 * would make either gesture destroy the other.
 */
export type Region = { fromTick: number, toTick: number, };

/**
 * One entry in the searchable roster (PRD § 3 Indexes, § 4 `roster_summary`).
 *
 * Everything here except identity is read from the model's **own** file rather
 * than from its resolved form. Inheritance is for musical parameters: merging
 * metadata would hand every artist their genre archetype's aliases, so typing
 * one alias would surface every artist that happens to extend it. `id`, `name`
 * and `type` come from the resolved model, which `inherit` already guarantees
 * are the model's own.
 */
export type RosterEntry = { id: string, name: string, aliases: Array<string>, type: ModelType, tier: Tier | null, genres: Array<string>, 
/**
 * Ids of the genre models this one works in, for cross-filtering the roster.
 *
 * Empty for a genre, and for an artist nobody has curated yet. ⛔ Not the
 * same thing as `genres`, which is free-text tags in a vocabulary of its
 * own — `rap`, `drill` — that name no model at all. Every id here has been
 * checked to name a real `genre`; see [`unknown_related_genres`].
 */
relatedGenres: Array<string>, era: string | null, 
/**
 * The producer's own model rather than a shipped one (TASK-040U).
 *
 * ⛔ **Set by whoever loaded it, not by the loader.** The engine has no idea
 * where a file came from — `load` is handed `(path, text)` pairs and its
 * rules are the same for all of them, which is exactly what makes a user
 * model first-class. The app knows which half it read from disk, so the app
 * is what marks them; this defaults to `false` and the plugin flips it.
 *
 * It carries no behaviour. A user model searches, generates, locks and
 * re-rolls identically — this is only so the roster can *say* it is yours.
 */
mine: boolean, };

/**
 * What `roster_summary` returns (PRD § 4).
 */
export type RosterSummary = { datasetVersion: string, entries: Array<RosterEntry>, problems: Array<DatasetProblem>, };

export type Scale = "major" | "dorian" | "phrygian" | "lydian" | "mixolydian" | "natural_minor" | "locrian" | "aeolian" | "major_pentatonic" | "minor_pentatonic" | "major_blues" | "blues" | "harmonic_minor" | "melodic_minor" | "harmonic_major" | "phrygian_dominant" | "dorian_sharp4" | "lydian_augmented" | "lydian_dominant" | "super_locrian" | "locrian_natural6" | "ionian_sharp5" | "ultralocrian" | "whole_tone" | "whole_half_diminished" | "half_whole_diminished" | "chromatic" | "hungarian_minor" | "eight_tone_spanish" | "bhairav" | "hirajoshi" | "in_sen" | "iwato" | "kumoi" | "pelog_selisir" | "pelog_tembung" | "messiaen_mode3" | "messiaen_mode4" | "messiaen_mode5" | "messiaen_mode6" | "messiaen_mode7";

/**
 * How a scale *feels*, for narrowing the picker by mood (TASK-041C).
 *
 * ⛔ **A property of the scale, not of the mood.** Mike's rule is that "dark
 * moods should only show dark scales" — and the only way that stays true as
 * scales are added is for each scale to declare its own character once, here,
 * with a test that every one of them has. The alternative, listing scales on
 * every mode, restates the same information in thirty-odd places and drifts.
 *
 * `Neutral` is a real answer rather than a fallback: the symmetric scales and
 * the Messiaen modes have no tonic third to be major or minor about, and
 * `uptempo`/`minimal` are tempo and density statements rather than emotional
 * ones, so they inherit the model's full list.
 */
export type ScaleCharacter = "dark" | "neutral" | "bright";

export type Section = { type: SectionKind, startBar: number, bars: number, 
/**
 * One pattern per part present in this section.
 */
patterns: { [key in Part]?: PatternRef }, 
/**
 * Beats of silence at the end of this section (TASK-066).
 *
 * The drop-out before a hook: the track cuts out for the last beat or two
 * so the hook lands. It is a property of *where the section sits* rather
 * than of its notes, because the clip underneath it loops — putting the
 * silence in the pattern would drop a beat out of every repeat instead of
 * once, at the end.
 */
dropOutBeats: number, 
/**
 * Whether this section fades across its length (TASK-066).
 *
 * Same reasoning: a decay that lived in the clip would reset on every
 * repeat, which is a stutter rather than an outro.
 */
decay: boolean, markers?: Array<string>, };

export type SectionKind = "intro" | "verse" | "preChorus" | "hook" | "bridge" | "outro";

/**
 * Everything a generator needs beyond the style model.
 */
export type SessionContext = { bpm: number, timeSigNum: number, timeSigDen: number, 
/**
 * Pitch class of the key root, 0 = C.
 */
keyRoot: number, scale: Scale, swing: Swing, bars: number, 
/**
 * Halves the perceived tempo — the drums sit at half speed against the
 * stated BPM, which is how most trap and drill models are notated.
 */
halfTime: boolean, humanize: Humanize, };

/**
 * What a model asks for, before a seed picks among the options it offers.
 *
 * The session chips need this the moment an artist is selected, which is
 * *before* there is a seed — and two of these fields are chosen by one.
 * `bpm`, `swing` and `half_time` are deterministic, so they arrive as values;
 * `keys` and `scales` are sampled, so they arrive as the authored lists. A
 * sampled key here would be a readout that silently changed under the user
 * the moment they pressed Generate (FR-002).
 */
export type SessionDefaults = { 
/**
 * The tempo a generation will use: `BpmSpec::nominal`, not a sample.
 */
bpm: number, 
/**
 * The tempo range the model authored, or `bpm` twice when it authored none
 * (TASK-158D).
 *
 * ⛔ **A range, because a single number is not what a producer is choosing
 * between.** *"tempo range"* is Mike's own word in TASK-158D: an artist who
 * works at 68–96 and one who works at 138–142 are different propositions at
 * the same nominal 82, and the pane exists so that is visible before
 * Generate rather than after.
 *
 * ⚠ **Not overwritten by the host's tempo the way `bpm` is.** That
 * substitution is TASK-033's, and it is right for "what will this come out
 * at" — but the range is a fact about the *model*, and replacing it with the
 * DAW's one tempo would say the artist only ever works there.
 */
bpmMin: number, bpmMax: number, 
/**
 * Which parts this model will actually write notes for (TASK-158D).
 *
 * See [`parts_of`] — this is the "and does **not** cover" half of what the
 * detail pane owes a producer.
 */
parts: Array<Part>, 
/**
 * Key names the model draws from, in authored order. Empty when it
 * authors none, in which case the engine's own default key applies.
 */
keys: Array<string>, 
/**
 * Scales the model draws from, in authored order.
 */
scales: Array<Scale>, swing: Swing, halfTime: boolean, 
/**
 * The moods this model offers, in authored order (TASK-040V).
 *
 * Empty for a model with no `modes` block, which is most of them — the
 * chip is hidden rather than shown offering only "Any". Names only: the
 * overrides behind them are the engine's business, and the UI picks by
 * name.
 */
moods?: Array<string>, };

/**
 * What a caller may pin instead of letting the model choose it.
 *
 * Everything is optional: an override the user has not touched must stay
 * absent rather than arrive as a default, or the artist's own value is
 * silently replaced by whatever the UI happened to initialise (PRD § 4
 * `SessionOverrides`).
 */
export type SessionOverrides = { bpm: number | null, 
/**
 * Pitch class, 0 = C.
 */
keyRoot: number | null, scale: Scale | null, swing: number | null, bars: number | null, halfTime: boolean | null, 
/**
 * The clip's own meter, when the producer set one (TASK-041E).
 *
 * ⛔ **Absent means "whatever the host is in", not 4/4.** Inside a DAW the
 * meter comes from the project, and a default here would silently drag a
 * 6/8 session back to common time on the next Generate. Set, it wins — a
 * producer writing a 3/4 clip in a 4/4 project has been more specific than
 * the project.
 */
timeSigNum: number | null, timeSigDen: number | null, };

/**
 * A full arrangement — what Song Mode produces and what the multi-track SMF
 * export walks.
 */
export type Song = { id: string, artistId: string, seed: string, bpm: number, keyRoot: number, scale: Scale, sections: Array<Section>, 
/**
 * Time signature, carried so a song reads without its `SessionContext`.
 */
timeSigNum: number, timeSigDen: number, 
/**
 * Every pattern the sections name, by [`PatternRef::pattern_id`].
 *
 * ⛔ **A `PatternRef` is an id, and until this existed nothing anywhere
 * held what the id named** — a `Song` described which pattern played where
 * and could not answer what any of them was, so it could not be drawn,
 * exported or played.
 *
 * A store rather than a `Pattern` inline in each section, because sharing
 * is the point: verse 1 and verse 2 are the same beat, and in these genres
 * that is the rule rather than an optimisation. One entry per distinct
 * pattern is also what makes a re-roll of one section a change to one
 * section — the UI repoints that section's ref instead of editing a
 * pattern two sections are looking at.
 */
patterns: { [key in string]?: Pattern }, ppq: number, };

/**
 * One part a file was separated into.
 */
export type SplitPart = { part: Part, pattern: Pattern, reason: SplitReason, 
/**
 * How many notes landed here, so the page can show it without walking lanes.
 */
notes: number, };

/**
 * Why [`split`] put a voice on the part it did.
 *
 * ⛔⛔ **The reason travels with the result, and that is a requirement rather
 * than a nicety.** TASK-058D states it for the audio path and it applies here:
 * *"the UI names what it detected … and never presents a guess as a
 * transcription"*, so *"a wrong guess is one click to redirect rather than a
 * silent mis-file."* Two of these reasons are facts about the file and three are
 * measurements — a producer is owed the difference.
 */
export type SplitReason = "drumChannel" | "kitShape" | "polyphonic" | "lowestVoice" | "highestVoice" | "innerVoice" | "splitByPitch" | "fromName";

/**
 * MPC-style swing. `0.50` is straight and `0.667` is fully triplet; the
 * research constants cluster at 0.54–0.66 (PRD § 3, research ch. 1).
 */
export type Swing = { grid: SwingGrid, amount: number, };

/**
 * The grid swing is applied against.
 */
export type SwingGrid = "eighth" | "sixteenth";

export type Tier = "flagship" | "standard" | "inherited";
