// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Performance marking. Carries intent the raw velocity cannot: a ghost note
 * and a quiet main hit are the same number but not the same musical event.
 */
export type Articulation = "ghost" | "accent" | "legato" | "staccato" | "roll";

/**
 * A model the app could not use, in the form the UI reports it (FR-001).
 *
 * A list rather than a count, because a badge saying "3" tells a user nothing
 * they can act on — the file and the reason do.
 */
export type DatasetProblem = { 
/**
 * The file it came from, or the model id when the failure was in the merge.
 */
source: string, message: string, };

/**
 * How far generated notes are pulled off the grid, and how much velocities
 * vary. Jitter is per lane because a hat and a kick do not breathe alike.
 */
export type Humanize = { 
/**
 * `1.0` snaps hard to the grid; `0.0` leaves the raw performance offset.
 */
quantizeStrength: number, 
/**
 * Fractional velocity spread, e.g. `0.12` = ±12%.
 */
velocityVar: number, 
/**
 * Per-lane timing jitter in milliseconds.
 */
timingJitterMs?: { [key in Lane]?: number }, };

/**
 * A voice within a pattern. Drum parts use several; melodic parts use one.
 */
export type Lane = "kick" | "snare" | "clap" | "closedHat" | "openHat" | "rim" | "snap" | "perc" | "bass808" | "melody" | "counter" | "bass" | "chords";

export type LaneTrack = { lane: Lane, notes: Array<Note>, };

export type ModelType = "artist" | "genre";

/**
 * A single note event. Ticks are absolute from the start of the pattern.
 */
export type Note = { startTick: number, lenTicks: number, 
/**
 * MIDI note number, 0–127.
 */
pitch: number, 
/**
 * MIDI velocity, 1–127.
 */
vel: number, 
/**
 * What the model itself wrote here, before [`crate::humanize`] spread it
 * (TASK-041V).
 *
 * ⛔ **The velocity lane's "reset" needs this and cannot recompute it.**
 * Resetting a cap has to put back the value that note's own lane tier
 * asked for — a ghost note's 40, an accent's 120 — and by the time anyone
 * can see the lane, `vary` has already spread it by a random factor that
 * is not invertible. Resetting to a flat 100 instead would quietly delete
 * the accent pattern that is the difference between a played pattern and a
 * programmed one, using the control whose whole promise is "put it back".
 *
 * `None` on a note nobody generated — one the producer drew — where there
 * is no model opinion to return to.
 */
modelVel?: number | null, 
/**
 * 808 slide target. The note glides to this pitch; the writer emits the
 * overlap convention the sampler reads as portamento.
 */
slideToPitch?: number | null, articulation?: Articulation | null, };

/**
 * The five generated parts. `Drums` covers the whole kit including the 808,
 * which doubles as the bassline lane in trap-family styles.
 */
export type Part = "drums" | "melody" | "counter" | "bass" | "chords";

/**
 * One generated clip for one part.
 */
export type Pattern = { id: string, part: Part, 
/**
 * The style model this came from — an artist or a genre archetype.
 */
artistId: string, seed: string, bars: number, bpm: number, timeSigNum: number, timeSigDen: number, 
/**
 * Pitch class of the key root, 0 = C.
 */
keyRoot: number, scale: Scale, lanes: Array<LaneTrack>, ppq: number, 
/**
 * The mode this was generated in, when the model offers any (TASK-040V).
 *
 * Carried on the pattern because a mood picked by the seed is otherwise
 * invisible: "Any" has to be able to say *which* one it landed on, for the
 * same reason the seed box echoes back the seed it used. `None` means the
 * model offers no modes, not that one was declined.
 */
mood?: string | null, 
/**
 * What the transport repeats, in ticks (TASK-041E).
 *
 * `None` is the whole clip, which is what every pattern is until someone
 * drags a brace. Carried on the pattern rather than held beside it because
 * it is a property of the clip: it saves with the project, travels with a
 * preset, and an edited clip that forgot its own loop on reload would be
 * the kind of quiet loss nobody attributes to the right feature.
 */
loopRegion?: Region | null, 
/**
 * The clip's own start and end, independent of the loop.
 */
clipRegion?: Region | null, };

export type PatternRef = { patternId: string, };

/**
 * A span of a clip, in absolute ticks (TASK-041E).
 *
 * Used for both the loop brace and the clip's own start and end, which are
 * deliberately two different things: a producer loops bar 2 of a four-bar idea
 * to work on it, and trims the clip to bars 1–3 to keep it. One field for both
 * would make either gesture destroy the other.
 */
export type Region = { fromTick: number, toTick: number, };

/**
 * One entry in the searchable roster (PRD § 3 Indexes, § 4 `roster_summary`).
 *
 * Everything here except identity is read from the model's **own** file rather
 * than from its resolved form. Inheritance is for musical parameters: merging
 * metadata would hand every artist their genre archetype's aliases, so typing
 * one alias would surface every artist that happens to extend it. `id`, `name`
 * and `type` come from the resolved model, which `inherit` already guarantees
 * are the model's own.
 */
export type RosterEntry = { id: string, name: string, aliases: Array<string>, type: ModelType, tier: Tier | null, genres: Array<string>, 
/**
 * Ids of the genre models this one works in, for cross-filtering the roster.
 *
 * Empty for a genre, and for an artist nobody has curated yet. ⛔ Not the
 * same thing as `genres`, which is free-text tags in a vocabulary of its
 * own — `rap`, `drill` — that name no model at all. Every id here has been
 * checked to name a real `genre`; see [`unknown_related_genres`].
 */
relatedGenres: Array<string>, era: string | null, };

/**
 * What `roster_summary` returns (PRD § 4).
 */
export type RosterSummary = { datasetVersion: string, entries: Array<RosterEntry>, problems: Array<DatasetProblem>, };

export type Scale = "major" | "dorian" | "phrygian" | "lydian" | "mixolydian" | "natural_minor" | "locrian" | "aeolian" | "major_pentatonic" | "minor_pentatonic" | "major_blues" | "blues" | "harmonic_minor" | "melodic_minor" | "harmonic_major" | "phrygian_dominant" | "dorian_sharp4" | "lydian_augmented" | "lydian_dominant" | "super_locrian" | "locrian_natural6" | "ionian_sharp5" | "ultralocrian" | "whole_tone" | "whole_half_diminished" | "half_whole_diminished" | "chromatic" | "hungarian_minor" | "eight_tone_spanish" | "bhairav" | "hirajoshi" | "in_sen" | "iwato" | "kumoi" | "pelog_selisir" | "pelog_tembung" | "messiaen_mode3" | "messiaen_mode4" | "messiaen_mode5" | "messiaen_mode6" | "messiaen_mode7";

/**
 * How a scale *feels*, for narrowing the picker by mood (TASK-041C).
 *
 * ⛔ **A property of the scale, not of the mood.** Mike's rule is that "dark
 * moods should only show dark scales" — and the only way that stays true as
 * scales are added is for each scale to declare its own character once, here,
 * with a test that every one of them has. The alternative, listing scales on
 * every mode, restates the same information in thirty-odd places and drifts.
 *
 * `Neutral` is a real answer rather than a fallback: the symmetric scales and
 * the Messiaen modes have no tonic third to be major or minor about, and
 * `uptempo`/`minimal` are tempo and density statements rather than emotional
 * ones, so they inherit the model's full list.
 */
export type ScaleCharacter = "dark" | "neutral" | "bright";

export type Section = { type: SectionKind, startBar: number, bars: number, 
/**
 * One pattern per part present in this section.
 */
patterns: { [key in Part]?: PatternRef }, markers?: Array<string>, };

export type SectionKind = "intro" | "verse" | "hook" | "bridge" | "outro";

/**
 * Everything a generator needs beyond the style model.
 */
export type SessionContext = { bpm: number, timeSigNum: number, timeSigDen: number, 
/**
 * Pitch class of the key root, 0 = C.
 */
keyRoot: number, scale: Scale, swing: Swing, bars: number, 
/**
 * Halves the perceived tempo — the drums sit at half speed against the
 * stated BPM, which is how most trap and drill models are notated.
 */
halfTime: boolean, humanize: Humanize, };

/**
 * What a model asks for, before a seed picks among the options it offers.
 *
 * The session chips need this the moment an artist is selected, which is
 * *before* there is a seed — and two of these fields are chosen by one.
 * `bpm`, `swing` and `half_time` are deterministic, so they arrive as values;
 * `keys` and `scales` are sampled, so they arrive as the authored lists. A
 * sampled key here would be a readout that silently changed under the user
 * the moment they pressed Generate (FR-002).
 */
export type SessionDefaults = { 
/**
 * The tempo a generation will use: `BpmSpec::nominal`, not a sample.
 */
bpm: number, 
/**
 * Key names the model draws from, in authored order. Empty when it
 * authors none, in which case the engine's own default key applies.
 */
keys: Array<string>, 
/**
 * Scales the model draws from, in authored order.
 */
scales: Array<Scale>, swing: Swing, halfTime: boolean, 
/**
 * The moods this model offers, in authored order (TASK-040V).
 *
 * Empty for a model with no `modes` block, which is most of them — the
 * chip is hidden rather than shown offering only "Any". Names only: the
 * overrides behind them are the engine's business, and the UI picks by
 * name.
 */
moods?: Array<string>, };

/**
 * What a caller may pin instead of letting the model choose it.
 *
 * Everything is optional: an override the user has not touched must stay
 * absent rather than arrive as a default, or the artist's own value is
 * silently replaced by whatever the UI happened to initialise (PRD § 4
 * `SessionOverrides`).
 */
export type SessionOverrides = { bpm: number | null, 
/**
 * Pitch class, 0 = C.
 */
keyRoot: number | null, scale: Scale | null, swing: number | null, bars: number | null, halfTime: boolean | null, 
/**
 * The clip's own meter, when the producer set one (TASK-041E).
 *
 * ⛔ **Absent means "whatever the host is in", not 4/4.** Inside a DAW the
 * meter comes from the project, and a default here would silently drag a
 * 6/8 session back to common time on the next Generate. Set, it wins — a
 * producer writing a 3/4 clip in a 4/4 project has been more specific than
 * the project.
 */
timeSigNum: number | null, timeSigDen: number | null, };

/**
 * A full arrangement — what Song Mode produces and what the multi-track SMF
 * export walks.
 */
export type Song = { id: string, artistId: string, seed: string, bpm: number, keyRoot: number, scale: Scale, sections: Array<Section>, ppq: number, };

/**
 * MPC-style swing. `0.50` is straight and `0.667` is fully triplet; the
 * research constants cluster at 0.54–0.66 (PRD § 3, research ch. 1).
 */
export type Swing = { grid: SwingGrid, amount: number, };

/**
 * The grid swing is applied against.
 */
export type SwingGrid = "eighth" | "sixteenth";

export type Tier = "flagship" | "standard" | "inherited";
