// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Performance marking. Carries intent the raw velocity cannot: a ghost note
 * and a quiet main hit are the same number but not the same musical event.
 */
export type Articulation = "ghost" | "accent" | "legato" | "staccato" | "roll";

/**
 * A model the app could not use, in the form the UI reports it (FR-001).
 *
 * A list rather than a count, because a badge saying "3" tells a user nothing
 * they can act on — the file and the reason do.
 */
export type DatasetProblem = { 
/**
 * The file it came from, or the model id when the failure was in the merge.
 */
source: string, message: string, };

/**
 * How far generated notes are pulled off the grid, and how much velocities
 * vary. Jitter is per lane because a hat and a kick do not breathe alike.
 */
export type Humanize = { 
/**
 * `1.0` snaps hard to the grid; `0.0` leaves the raw performance offset.
 */
quantizeStrength: number, 
/**
 * Fractional velocity spread, e.g. `0.12` = ±12%.
 */
velocityVar: number, 
/**
 * Per-lane timing jitter in milliseconds.
 */
timingJitterMs?: { [key in Lane]?: number }, };

/**
 * A voice within a pattern. Drum parts use several; melodic parts use one.
 */
export type Lane = "kick" | "snare" | "clap" | "closedHat" | "openHat" | "rim" | "snap" | "perc" | "bass808" | "melody" | "counter" | "bass" | "chords";

export type LaneTrack = { lane: Lane, notes: Array<Note>, };

export type ModelType = "artist" | "genre";

/**
 * A single note event. Ticks are absolute from the start of the pattern.
 */
export type Note = { startTick: number, lenTicks: number, 
/**
 * MIDI note number, 0–127.
 */
pitch: number, 
/**
 * MIDI velocity, 1–127.
 */
vel: number, 
/**
 * 808 slide target. The note glides to this pitch; the writer emits the
 * overlap convention the sampler reads as portamento.
 */
slideToPitch?: number | null, articulation?: Articulation | null, };

/**
 * The five generated parts. `Drums` covers the whole kit including the 808,
 * which doubles as the bassline lane in trap-family styles.
 */
export type Part = "drums" | "melody" | "counter" | "bass" | "chords";

/**
 * One generated clip for one part.
 */
export type Pattern = { id: string, part: Part, 
/**
 * The style model this came from — an artist or a genre archetype.
 */
artistId: string, seed: string, bars: number, bpm: number, timeSigNum: number, timeSigDen: number, 
/**
 * Pitch class of the key root, 0 = C.
 */
keyRoot: number, scale: Scale, lanes: Array<LaneTrack>, ppq: number, };

export type PatternRef = { patternId: string, };

/**
 * One entry in the searchable roster (PRD § 3 Indexes, § 4 `roster_summary`).
 *
 * Everything here except identity is read from the model's **own** file rather
 * than from its resolved form. Inheritance is for musical parameters: merging
 * metadata would hand every artist their genre archetype's aliases, so typing
 * one alias would surface every artist that happens to extend it. `id`, `name`
 * and `type` come from the resolved model, which `inherit` already guarantees
 * are the model's own.
 */
export type RosterEntry = { id: string, name: string, aliases: Array<string>, type: ModelType, tier: Tier | null, genres: Array<string>, era: string | null, };

/**
 * What `roster_summary` returns (PRD § 4).
 */
export type RosterSummary = { datasetVersion: string, entries: Array<RosterEntry>, problems: Array<DatasetProblem>, };

export type Scale = "natural_minor" | "harmonic_minor" | "phrygian" | "phrygian_dominant" | "dorian" | "major" | "mixolydian" | "lydian" | "aeolian" | "minor_pentatonic" | "major_pentatonic" | "blues";

export type Section = { type: SectionKind, startBar: number, bars: number, 
/**
 * One pattern per part present in this section.
 */
patterns: { [key in Part]?: PatternRef }, markers?: Array<string>, };

export type SectionKind = "intro" | "verse" | "hook" | "bridge" | "outro";

/**
 * Everything a generator needs beyond the style model.
 */
export type SessionContext = { bpm: number, timeSigNum: number, timeSigDen: number, 
/**
 * Pitch class of the key root, 0 = C.
 */
keyRoot: number, scale: Scale, swing: Swing, bars: number, 
/**
 * Halves the perceived tempo — the drums sit at half speed against the
 * stated BPM, which is how most trap and drill models are notated.
 */
halfTime: boolean, humanize: Humanize, };

/**
 * A full arrangement — what Song Mode produces and what the multi-track SMF
 * export walks.
 */
export type Song = { id: string, artistId: string, seed: string, bpm: number, keyRoot: number, scale: Scale, sections: Array<Section>, ppq: number, };

/**
 * MPC-style swing. `0.50` is straight and `0.667` is fully triplet; the
 * research constants cluster at 0.54–0.66 (PRD § 3, research ch. 1).
 */
export type Swing = { grid: SwingGrid, amount: number, };

/**
 * The grid swing is applied against.
 */
export type SwingGrid = "eighth" | "sixteenth";

export type Tier = "flagship" | "standard" | "inherited";
