import { beforeEach, expect, it, vi } from 'vitest';

import type { Part, Song } from '../lib/ipc-types';

/**
 * The arrangement document (TASK-067).
 *
 * ⛔ **The half these tests exist for is persistence, and it is invisible.**
 * Every gesture in the timeline already has a spec that asserts the resulting
 * geometry; none of them can see whether the result would survive closing the
 * project, which is the failure three consecutive handoffs have written down.
 * So what is asserted here is the *payload* — that an edited song is in the one
 * value the host saves, and that an unedited one is deliberately not.
 */

const invoke = vi.fn();
vi.mock('../lib/ipc', () => ({
  invoke: (command: string, args?: unknown) => invoke(command, args),
}));

// The plugin gate: `persist()` is a no-op in a browser, so without this the
// payload assertions below would pass by never being sent at all.
vi.mock('../lib/ipc-plugin', async (importOriginal) => ({
  ...(await importOriginal<typeof import('../lib/ipc-plugin')>()),
  isPlugin: () => true,
}));

const { useSong } = await import('./song');
const { useSession } = await import('./session');
const { useHistory, canRedo, canUndo } = await import('./history');

/** Two sections, the second sharing nothing with the first. */
function song(): Song {
  const clip = (id: string) => ({
    id,
    part: 'drums' as Part,
    artistId: 'trap',
    seed: '7',
    bars: 4,
    bpm: 140,
    timeSigNum: 4,
    timeSigDen: 4,
    keyRoot: 6,
    scale: 'natural_minor' as const,
    lanes: [],
    ppq: 960,
    mood: null,
    loopRegion: null,
    clipRegion: null,
  });
  return {
    id: 'trap-song-7',
    artistId: 'trap',
    seed: '7',
    bpm: 140,
    keyRoot: 6,
    scale: 'natural_minor',
    sections: [
      {
        type: 'intro',
        startBar: 0,
        bars: 4,
        patterns: { drums: { patternId: 'a' } } as Song['sections'][number]['patterns'],
        dropOutBeats: 0,
        decay: false,
        markers: [],
      },
      {
        type: 'hook',
        startBar: 4,
        bars: 8,
        patterns: { drums: { patternId: 'b' } } as Song['sections'][number]['patterns'],
        dropOutBeats: 0,
        decay: false,
        markers: [],
      },
    ],
    timeSigNum: 4,
    timeSigDen: 4,
    patterns: { a: clip('a'), b: clip('b') },
    ppq: 960,
  };
}

/** The last `save_session_state` payload, or null if none was sent. */
function lastSave(): Record<string, unknown> | null {
  const calls = invoke.mock.calls.filter(([command]) => command === 'save_session_state');
  const last = calls.at(-1);
  return last ? ((last[1] as { session: Record<string, unknown> }).session ?? null) : null;
}

beforeEach(() => {
  invoke.mockReset();
  invoke.mockResolvedValue(undefined);
  vi.useFakeTimers();
  useSong.setState({
    song: null,
    edited: false,
    generating: false,
    error: null,
    selection: [],
    anchor: null,
    clipboard: null,
    locks: [],
    // ⛔ Reset with the rest. Left out, the solo test's `soloParts` survived into
    // the mute test below it and made a *correct* implementation look wrong —
    // and would equally have let a broken one pass, which is the half that
    // matters.
    loopSection: null,
    mutedParts: [],
    soloParts: [],
    audition: null,
    drillPatternId: null,
    structure: null,
  });
  useSession.setState({ pattern: null, edited: false });
});

/** Run the 300 ms save debounce out. */
function flushSave() {
  vi.runAllTimers();
}

/**
 * Put an arrangement on screen with a history baseline behind it.
 *
 * ⛔ Armed, not merely present. `history.record` is a no-op until `arm` has
 * established the point undo cannot go behind, so a test that skipped this
 * would record nothing and every undo assertion below would pass by never
 * having anything to undo.
 */
function armedWith(current = song()) {
  useSong.setState({ song: current });
  useHistory.getState().arm({
    selectedId: 'trap',
    seed: '7',
    bars: 4,
    pins: {
      bpm: null,
      keyRoot: null,
      scale: null,
      swing: null,
      timeSigNum: null,
      timeSigDen: null,
    },
    autoSync: true,
    pattern: null,
    edited: false,
    mood: null,
    audioEnabled: true,
    mutedLanes: [],
    song: current,
    songEdited: false,
  });
  return current;
}

it('an edited arrangement is in the value the host saves', () => {
  useSong.setState({ song: song() });
  useSong.getState().resize(0, 8);
  flushSave();

  const saved = lastSave();
  expect(saved).not.toBeNull();
  expect(saved?.songEdited).toBe(true);
  expect((saved?.song as Song).sections[0].bars).toBe(8);
});

it('an unedited arrangement is deliberately not saved', () => {
  // ⛔ The property that keeps a project file small: a song still describable by
  // its seed is regenerated by pressing Generate, so storing kilobytes of notes
  // to restore it would buy nothing — and would stop the project picking up
  // engine improvements, which `state.rs` documents as the whole trade.
  useSong.setState({ song: song(), edited: false });
  useSession.getState().setSeed('12');
  flushSave();

  const saved = lastSave();
  expect(saved).not.toBeNull();
  expect(saved).not.toHaveProperty('song');
  expect(saved?.songEdited).toBeUndefined();
});

it('a resize that changes nothing is not an edit and is not saved as one', () => {
  // `clips.ts` returns the same object on a no-op, which is what makes `edited`
  // honest. Marking it would tell the producer their song no longer matches its
  // seed when it does — and would put the whole arrangement in the project file
  // for a gesture that did nothing.
  useSong.setState({ song: song() });
  useSong.getState().resize(0, 4);
  flushSave();

  expect(useSong.getState().edited).toBe(false);
  expect(lastSave()).toBeNull();
});

it('a re-roll resolves the producer’s locks into the parts the engine wants', async () => {
  // The engine is deliberately lock-agnostic — it takes a list of parts to
  // leave alone — so everything about *how* a lock was expressed is resolved on
  // this side. A lock on another section must not narrow this one's re-roll.
  const current = song();
  invoke.mockResolvedValue(current);
  useSong.setState({ song: current, locks: ['0:drums', '1:melody'] });

  await useSong.getState().reroll(0, null);

  const call = invoke.mock.calls.find(([command]) => command === 'reroll_section');
  expect(call).toBeDefined();
  expect((call?.[1] as { request: { locked: Part[] } }).request.locked).toEqual(['drums']);
});

it('a re-roll marks the arrangement edited, because its seed no longer describes it', async () => {
  // ⛔ The edit that is easiest to lose: nothing about a re-roll *looks* like an
  // edit. The timeline redraws and the geometry is identical, so without this
  // the section would silently revert to the seed's own notes on reopen.
  const current = song();
  invoke.mockResolvedValue(current);
  useSong.setState({ song: current });

  await useSong.getState().reroll(1, null);
  flushSave();

  expect(useSong.getState().edited).toBe(true);
  expect(lastSave()?.songEdited).toBe(true);
});

it('generating a fresh song drops the locks placed on the old one', async () => {
  // A lock names a section index and a part. A fresh generation has neither the
  // same sections nor the same clips, so a kept lock would pin whatever landed
  // at that index — which is not what the producer pinned.
  invoke.mockResolvedValue(song());
  useSong.setState({ song: song(), locks: ['0:drums'] });

  await useSong
    .getState()
    .generate({ styleId: 'trap', seed: '9', pins: {} as never, mood: null });

  expect(useSong.getState().locks).toEqual([]);
});

it('a section lock covers every clip in it, and unlocks as one', () => {
  useSong.setState({ song: song() });
  useSong.getState().toggleSectionLock(1);
  expect(useSong.getState().locks).toEqual(['1:drums']);

  useSong.getState().toggleSectionLock(1);
  expect(useSong.getState().locks).toEqual([]);
});

it('a row lock covers that part in every section that plays it', () => {
  useSong.setState({ song: song() });
  useSong.getState().toggleRowLock('drums');
  expect(useSong.getState().locks.sort()).toEqual(['0:drums', '1:drums']);
});

// ---------------------------------------------------------------------------
// Arrangement undo (TASK-063B). One stack, shared with the session.
// ---------------------------------------------------------------------------

it('Ctrl+Z steps an arrangement edit back', () => {
  armedWith();
  useSong.getState().resize(0, 8);
  expect(useSong.getState().song?.sections[0].bars).toBe(8);

  useSession.getState().undo();

  expect(useSong.getState().song?.sections[0].bars).toBe(4);
  // And the section after it moved back with it, because a resize retiles.
  expect(useSong.getState().song?.sections[1].startBar).toBe(4);
});

it('an undone arrangement edit is redoable', () => {
  armedWith();
  useSong.getState().resize(0, 8);
  useSession.getState().undo();
  useSession.getState().redo();

  expect(useSong.getState().song?.sections[0].bars).toBe(8);
});

it('undoing an arrangement edit does not step the session back', () => {
  // ⛔ The regression that made this shortcut a deliberate no-op in the first
  // place: Ctrl+Z on the Song tab used to revert a seed keystroke or a pin made
  // on another tab while the arrangement stayed exactly as it was — damage the
  // producer would only find later, somewhere else.
  armedWith();
  useSession.setState({ seed: '4242' });
  useSong.getState().resize(0, 8);

  useSession.getState().undo();

  expect(useSong.getState().song?.sections[0].bars).toBe(4);
  expect(useSession.getState().seed).toBe('4242');
});

it('a restore is not recorded as a fresh edit', () => {
  // ⛔ Without the `applying` guard in `noteDocumentChange`, restoring the song
  // would record the restored state as a new step — so every Ctrl+Z would push
  // an entry as it popped one and the stack could never be walked out of.
  armedWith();
  useSong.getState().resize(0, 8);
  useSong.getState().resize(0, 12);

  useSession.getState().undo();
  useSession.getState().undo();

  expect(useSong.getState().song?.sections[0].bars).toBe(4);
  expect(canUndo(useHistory.getState())).toBe(false);
  expect(canRedo(useHistory.getState())).toBe(true);
});

it('two arrangement edits in quick succession are two undo steps', () => {
  // ⛔ `song` is DISCRETE for the same reason `mutedLanes` is. Coalescing suits
  // a value being typed toward; deleting a clip and then cloning a section
  // inside 600 ms is two intentions, and merging them would make the state
  // between them unreachable.
  armedWith();
  useSong.getState().resize(0, 8);
  useSong.getState().resize(1, 12);

  useSession.getState().undo();
  expect(useSong.getState().song?.sections[1].bars).toBe(8);
  expect(useSong.getState().song?.sections[0].bars).toBe(8);

  useSession.getState().undo();
  expect(useSong.getState().song?.sections[0].bars).toBe(4);
});

// ---------------------------------------------------------------------------
// Playback (TASK-072). The arrangement reaching the audio thread.
// ---------------------------------------------------------------------------

/** The last `arm_song` request, or null. */
function lastArm(): { song: Song; loopSection: number | null; parts: Part[] | null } | null {
  const calls = invoke.mock.calls.filter(([command]) => command === 'arm_song');
  const last = calls.at(-1);
  return last
    ? (last[1] as { request: { song: Song; loopSection: number | null; parts: Part[] | null } })
        .request
    : null;
}

it('every arrangement edit re-arms what is playing', () => {
  // ⛔ A resize retiles the whole song, so the clip already on the audio thread
  // describes bars that have moved. Without this the producer goes on hearing
  // the arrangement they had before while the timeline draws the one they made.
  useSong.setState({ song: song() });
  useSong.getState().resize(0, 8);

  expect(lastArm()?.song.sections[0].bars).toBe(8);
});

it('undo re-arms the arrangement it restored', () => {
  armedWith();
  useSong.getState().resize(0, 8);
  useSession.getState().undo();

  expect(lastArm()?.song.sections[0].bars).toBe(4);
});

it('a section loop is sent as an index, and toggles off', () => {
  useSong.setState({ song: song() });
  useSong.getState().setLoopSection(1);
  expect(lastArm()?.loopSection).toBe(1);

  useSong.getState().setLoopSection(null);
  expect(lastArm()?.loopSection).toBeNull();
});

it('the whole record sends no part filter at all', () => {
  // `null` rather than "every part", so the common case takes the engine's
  // whole-song path and there is one less list that can be wrong.
  useSong.setState({ song: song() });
  useSong.getState().armSong();
  expect(lastArm()?.parts).toBeNull();
});

it('solo wins over mute', () => {
  // ⛔ What every DAW does, and not merely a convention: a producer soloing the
  // drums has usually muted something earlier and forgotten, and making them
  // undo that first would mean solo sometimes did nothing while the row stayed
  // lit saying otherwise.
  useSong.setState({ song: song(), mutedParts: ['drums'] });
  useSong.getState().togglePartSolo('drums');

  expect(lastArm()?.parts).toEqual(['drums']);
});

it('muting a part leaves the others playing', () => {
  useSong.setState({ song: song() });
  useSong.getState().togglePartMute('drums');
  expect(lastArm()?.parts).toEqual([]);
});

it('generating a fresh song drops the loop, because the indices moved', async () => {
  invoke.mockResolvedValue(song());
  useSong.setState({ song: song(), loopSection: 1 });

  await useSong
    .getState()
    .generate({ styleId: 'trap', seed: '9', pins: {} as never, mood: null });
  expect(useSong.getState().loopSection).toBeNull();
});

// ---------------------------------------------------------------------------
// Timeline interactions (TASK-071): audition, re-roll, drill-in.
// ---------------------------------------------------------------------------

it('an audition arms that one cell, looping its section', () => {
  useSong.setState({ song: song() });
  useSong.getState().auditionClip({ sectionIndex: 1, part: 'drums' });

  expect(lastArm()?.loopSection).toBe(1);
  expect(lastArm()?.parts).toEqual(['drums']);
});

it('an audition overrides the loop and the solo while it lasts, then gives them back', () => {
  // ⛔ It has to override both, or "audition this cell" would play the cell
  // *and* whatever else was soloed. And it has to hand them back, or ending an
  // audition would silently drop settings the producer never touched.
  useSong.setState({ song: song(), loopSection: 0, soloParts: ['melody'] });
  useSong.getState().auditionClip({ sectionIndex: 1, part: 'drums' });
  expect(lastArm()?.loopSection).toBe(1);
  expect(lastArm()?.parts).toEqual(['drums']);

  useSong.getState().stopAudition();
  expect(lastArm()?.loopSection).toBe(0);
  expect(lastArm()?.parts).toEqual(['melody']);
});

it('auditioning the same cell twice is the way out of it', () => {
  useSong.setState({ song: song() });
  useSong.getState().auditionClip({ sectionIndex: 1, part: 'drums' });
  useSong.getState().auditionClip({ sectionIndex: 1, part: 'drums' });
  expect(useSong.getState().audition).toBeNull();
});

it('drilling into a clip opens it in its own editor', () => {
  useSong.setState({ song: song() });
  useSong.getState().drillInto({ sectionIndex: 0, part: 'drums' });

  expect(useSession.getState().pattern?.id).toBe('a');
  // ⛔ Marked edited, and it is not a guess: a clip lifted out of an arrangement
  // is not what *this session's* seed produces. Left false, the next save would
  // drop it and the next Generate would silently replace it.
  expect(useSession.getState().edited).toBe(true);
  expect(useSong.getState().drillPatternId).toBe('a');
});

it('editing a drilled-in clip writes back to the song', () => {
  // The roadmap's own requirement, and the half a drill-in is worthless
  // without: the producer edits in the roll and the arrangement has the edit.
  useSong.setState({ song: song() });
  useSong.getState().drillInto({ sectionIndex: 0, part: 'drums' });

  const open = useSession.getState().pattern;
  expect(open).not.toBeNull();
  useSession.getState().editPattern({ ...open!, bars: 8 });

  expect(useSong.getState().song?.patterns.a?.bars).toBe(8);
  expect(useSong.getState().edited).toBe(true);
});

it('generating on a part tab after drilling in does not overwrite the song', () => {
  // ⛔ A fresh generation is a *new* clip, not an edit of the song's — writing
  // it back would drop a whole section's arrangement into the timeline without
  // anybody asking for it. The id is what tells the two apart.
  useSong.setState({ song: song() });
  useSong.getState().drillInto({ sectionIndex: 0, part: 'drums' });

  const open = useSession.getState().pattern;
  useSession.getState().editPattern({ ...open!, id: 'something-else', bars: 8 });

  expect(useSong.getState().song?.patterns.a?.bars).toBe(4);
});

it('closing a drill-in stops the write-back', () => {
  useSong.setState({ song: song() });
  useSong.getState().drillInto({ sectionIndex: 0, part: 'drums' });
  useSong.getState().closeDrill();

  const open = useSession.getState().pattern;
  useSession.getState().editPattern({ ...open!, bars: 8 });
  expect(useSong.getState().song?.patterns.a?.bars).toBe(4);
});
