import { beforeEach, expect, it, vi } from 'vitest';

import type { Part, Song } from '../lib/ipc-types';

/**
 * The arrangement document (TASK-067).
 *
 * ⛔ **The half these tests exist for is persistence, and it is invisible.**
 * Every gesture in the timeline already has a spec that asserts the resulting
 * geometry; none of them can see whether the result would survive closing the
 * project, which is the failure three consecutive handoffs have written down.
 * So what is asserted here is the *payload* — that an edited song is in the one
 * value the host saves, and that an unedited one is deliberately not.
 */

const invoke = vi.fn();
vi.mock('../lib/ipc', () => ({
  invoke: (command: string, args?: unknown) => invoke(command, args),
}));

// The plugin gate: `persist()` is a no-op in a browser, so without this the
// payload assertions below would pass by never being sent at all.
vi.mock('../lib/ipc-plugin', async (importOriginal) => ({
  ...(await importOriginal<typeof import('../lib/ipc-plugin')>()),
  isPlugin: () => true,
}));

const { useSong } = await import('./song');
const { useSession } = await import('./session');
const { useHistory, canRedo, canUndo } = await import('./history');

/** Two sections, the second sharing nothing with the first. */
function song(): Song {
  const clip = (id: string) => ({
    id,
    part: 'drums' as Part,
    artistId: 'trap',
    seed: '7',
    bars: 4,
    bpm: 140,
    timeSigNum: 4,
    timeSigDen: 4,
    keyRoot: 6,
    scale: 'natural_minor' as const,
    lanes: [],
    ppq: 960,
    mood: null,
    loopRegion: null,
    clipRegion: null,
  });
  return {
    id: 'trap-song-7',
    artistId: 'trap',
    seed: '7',
    bpm: 140,
    keyRoot: 6,
    scale: 'natural_minor',
    sections: [
      {
        type: 'intro',
        startBar: 0,
        bars: 4,
        patterns: { drums: { patternId: 'a' } } as Song['sections'][number]['patterns'],
        dropOutBeats: 0,
        decay: false,
        markers: [],
      },
      {
        type: 'hook',
        startBar: 4,
        bars: 8,
        patterns: { drums: { patternId: 'b' } } as Song['sections'][number]['patterns'],
        dropOutBeats: 0,
        decay: false,
        markers: [],
      },
    ],
    timeSigNum: 4,
    timeSigDen: 4,
    patterns: { a: clip('a'), b: clip('b') },
    ppq: 960,
  };
}

/** The last `save_session_state` payload, or null if none was sent. */
function lastSave(): Record<string, unknown> | null {
  const calls = invoke.mock.calls.filter(([command]) => command === 'save_session_state');
  const last = calls.at(-1);
  return last ? ((last[1] as { session: Record<string, unknown> }).session ?? null) : null;
}

beforeEach(() => {
  invoke.mockReset();
  invoke.mockResolvedValue(undefined);
  vi.useFakeTimers();
  useSong.setState({
    song: null,
    edited: false,
    generating: false,
    error: null,
    selection: [],
    anchor: null,
    clipboard: null,
    locks: [],
  });
});

/** Run the 300 ms save debounce out. */
function flushSave() {
  vi.runAllTimers();
}

/**
 * Put an arrangement on screen with a history baseline behind it.
 *
 * ⛔ Armed, not merely present. `history.record` is a no-op until `arm` has
 * established the point undo cannot go behind, so a test that skipped this
 * would record nothing and every undo assertion below would pass by never
 * having anything to undo.
 */
function armedWith(current = song()) {
  useSong.setState({ song: current });
  useHistory.getState().arm({
    selectedId: 'trap',
    seed: '7',
    bars: 4,
    pins: {
      bpm: null,
      keyRoot: null,
      scale: null,
      swing: null,
      timeSigNum: null,
      timeSigDen: null,
    },
    autoSync: true,
    pattern: null,
    edited: false,
    mood: null,
    audioEnabled: true,
    mutedLanes: [],
    song: current,
    songEdited: false,
  });
  return current;
}

it('an edited arrangement is in the value the host saves', () => {
  useSong.setState({ song: song() });
  useSong.getState().resize(0, 8);
  flushSave();

  const saved = lastSave();
  expect(saved).not.toBeNull();
  expect(saved?.songEdited).toBe(true);
  expect((saved?.song as Song).sections[0].bars).toBe(8);
});

it('an unedited arrangement is deliberately not saved', () => {
  // ⛔ The property that keeps a project file small: a song still describable by
  // its seed is regenerated by pressing Generate, so storing kilobytes of notes
  // to restore it would buy nothing — and would stop the project picking up
  // engine improvements, which `state.rs` documents as the whole trade.
  useSong.setState({ song: song(), edited: false });
  useSession.getState().setSeed('12');
  flushSave();

  const saved = lastSave();
  expect(saved).not.toBeNull();
  expect(saved).not.toHaveProperty('song');
  expect(saved?.songEdited).toBeUndefined();
});

it('a resize that changes nothing is not an edit and is not saved as one', () => {
  // `clips.ts` returns the same object on a no-op, which is what makes `edited`
  // honest. Marking it would tell the producer their song no longer matches its
  // seed when it does — and would put the whole arrangement in the project file
  // for a gesture that did nothing.
  useSong.setState({ song: song() });
  useSong.getState().resize(0, 4);
  flushSave();

  expect(useSong.getState().edited).toBe(false);
  expect(lastSave()).toBeNull();
});

it('a re-roll resolves the producer’s locks into the parts the engine wants', async () => {
  // The engine is deliberately lock-agnostic — it takes a list of parts to
  // leave alone — so everything about *how* a lock was expressed is resolved on
  // this side. A lock on another section must not narrow this one's re-roll.
  const current = song();
  invoke.mockResolvedValue(current);
  useSong.setState({ song: current, locks: ['0:drums', '1:melody'] });

  await useSong.getState().reroll(0, null);

  const call = invoke.mock.calls.find(([command]) => command === 'reroll_section');
  expect(call).toBeDefined();
  expect((call?.[1] as { request: { locked: Part[] } }).request.locked).toEqual(['drums']);
});

it('a re-roll marks the arrangement edited, because its seed no longer describes it', async () => {
  // ⛔ The edit that is easiest to lose: nothing about a re-roll *looks* like an
  // edit. The timeline redraws and the geometry is identical, so without this
  // the section would silently revert to the seed's own notes on reopen.
  const current = song();
  invoke.mockResolvedValue(current);
  useSong.setState({ song: current });

  await useSong.getState().reroll(1, null);
  flushSave();

  expect(useSong.getState().edited).toBe(true);
  expect(lastSave()?.songEdited).toBe(true);
});

it('generating a fresh song drops the locks placed on the old one', async () => {
  // A lock names a section index and a part. A fresh generation has neither the
  // same sections nor the same clips, so a kept lock would pin whatever landed
  // at that index — which is not what the producer pinned.
  invoke.mockResolvedValue(song());
  useSong.setState({ song: song(), locks: ['0:drums'] });

  await useSong
    .getState()
    .generate({ styleId: 'trap', seed: '9', pins: {} as never, mood: null });

  expect(useSong.getState().locks).toEqual([]);
});

it('a section lock covers every clip in it, and unlocks as one', () => {
  useSong.setState({ song: song() });
  useSong.getState().toggleSectionLock(1);
  expect(useSong.getState().locks).toEqual(['1:drums']);

  useSong.getState().toggleSectionLock(1);
  expect(useSong.getState().locks).toEqual([]);
});

it('a row lock covers that part in every section that plays it', () => {
  useSong.setState({ song: song() });
  useSong.getState().toggleRowLock('drums');
  expect(useSong.getState().locks.sort()).toEqual(['0:drums', '1:drums']);
});

// ---------------------------------------------------------------------------
// Arrangement undo (TASK-063B). One stack, shared with the session.
// ---------------------------------------------------------------------------

it('Ctrl+Z steps an arrangement edit back', () => {
  armedWith();
  useSong.getState().resize(0, 8);
  expect(useSong.getState().song?.sections[0].bars).toBe(8);

  useSession.getState().undo();

  expect(useSong.getState().song?.sections[0].bars).toBe(4);
  // And the section after it moved back with it, because a resize retiles.
  expect(useSong.getState().song?.sections[1].startBar).toBe(4);
});

it('an undone arrangement edit is redoable', () => {
  armedWith();
  useSong.getState().resize(0, 8);
  useSession.getState().undo();
  useSession.getState().redo();

  expect(useSong.getState().song?.sections[0].bars).toBe(8);
});

it('undoing an arrangement edit does not step the session back', () => {
  // ⛔ The regression that made this shortcut a deliberate no-op in the first
  // place: Ctrl+Z on the Song tab used to revert a seed keystroke or a pin made
  // on another tab while the arrangement stayed exactly as it was — damage the
  // producer would only find later, somewhere else.
  armedWith();
  useSession.setState({ seed: '4242' });
  useSong.getState().resize(0, 8);

  useSession.getState().undo();

  expect(useSong.getState().song?.sections[0].bars).toBe(4);
  expect(useSession.getState().seed).toBe('4242');
});

it('a restore is not recorded as a fresh edit', () => {
  // ⛔ Without the `applying` guard in `noteDocumentChange`, restoring the song
  // would record the restored state as a new step — so every Ctrl+Z would push
  // an entry as it popped one and the stack could never be walked out of.
  armedWith();
  useSong.getState().resize(0, 8);
  useSong.getState().resize(0, 12);

  useSession.getState().undo();
  useSession.getState().undo();

  expect(useSong.getState().song?.sections[0].bars).toBe(4);
  expect(canUndo(useHistory.getState())).toBe(false);
  expect(canRedo(useHistory.getState())).toBe(true);
});

it('two arrangement edits in quick succession are two undo steps', () => {
  // ⛔ `song` is DISCRETE for the same reason `mutedLanes` is. Coalescing suits
  // a value being typed toward; deleting a clip and then cloning a section
  // inside 600 ms is two intentions, and merging them would make the state
  // between them unreachable.
  armedWith();
  useSong.getState().resize(0, 8);
  useSong.getState().resize(1, 12);

  useSession.getState().undo();
  expect(useSong.getState().song?.sections[1].bars).toBe(8);
  expect(useSong.getState().song?.sections[0].bars).toBe(8);

  useSession.getState().undo();
  expect(useSong.getState().song?.sections[0].bars).toBe(4);
});
