#!/usr/bin/env node
/**
 * Regenerates Appendix A of docs/dataset-protocol.md from `data/artists/`.
 *
 * The ledger answers one question that 500 files cannot answer by being listed:
 * "is this artist already encoded, and against which lane?" It is derived, so
 * it is regenerated rather than maintained — hand-editing it guarantees it
 * drifts from the data it claims to describe.
 *
 * `--check` is the CI half: it regenerates into memory and fails if the file on
 * disk differs. That is what stops a batch landing with a stale appendix.
 *
 * Grouped by lane (the first `extends` entry) rather than alphabetically,
 * because lane balance is the thing worth seeing at a glance — a roster with
 * 200 trap artists and 3 country ones is a roster with a hole in it, and an
 * alphabetical list hides that completely.
 *
 * Usage:
 *   node scripts/roster-ledger.mjs           # rewrite in place
 *   node scripts/roster-ledger.mjs --check   # fail if stale
 */

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const artistsDir = join(root, 'data', 'artists');
const docPath = join(root, 'docs', 'dataset-protocol.md');

const BEGIN = '<!-- ROSTER-LEDGER:BEGIN -->';
const END = '<!-- ROSTER-LEDGER:END -->';

/** Tier order for sorting — depth first, so the flagships read at the top. */
const TIER_RANK = { flagship: 0, standard: 1, inherited: 2, undefined: 3 };

function models() {
  return readdirSync(artistsDir)
    .filter((f) => f.endsWith('.json'))
    .map((f) => {
      const model = JSON.parse(readFileSync(join(artistsDir, f), 'utf8'));
      return {
        id: model.id,
        name: model.name,
        tier: model.tier,
        // A model with no `extends` sits on `_defaults` by definition, and
        // saying so is more useful than an empty cell.
        lane: model.extends?.[0] ?? '_defaults',
        confidence: model.confidence,
        aliases: model.aliases?.length ?? 0,
      };
    });
}

function escapePipes(text) {
  return String(text ?? '—').replaceAll('|', '\\|');
}

function render(rows) {
  const byLane = new Map();
  for (const row of rows) {
    if (!byLane.has(row.lane)) byLane.set(row.lane, []);
    byLane.get(row.lane).push(row);
  }

  // ⛔ **`tier` is optional in the schema**, so a model without one used to fall
  // through every counter and the header printed three numbers that did not sum
  // to the stated total — beside a table row showing `—`. `--check` compares
  // against the same generated text, so it reported "current" and the
  // self-contradicting appendix would have shipped to the docs site.
  const tiers = { flagship: 0, standard: 0, inherited: 0, untiered: 0 };
  for (const row of rows) {
    if (row.tier in tiers && row.tier !== 'untiered') tiers[row.tier] += 1;
    else tiers.untiered += 1;
  }

  const out = [
    `**${rows.length} artists** — ${tiers.flagship} flagship, ${tiers.standard} standard, ` +
      `${tiers.inherited} inherited` +
      (tiers.untiered > 0 ? `, ${tiers.untiered} with no tier` : '') +
      `, across ${byLane.size} lanes.`,
    '',
    '*Generated by `scripts/roster-ledger.mjs`. Do not hand-edit.*',
    '',
  ];

  for (const lane of [...byLane.keys()].sort()) {
    const laneRows = byLane.get(lane).sort((a, b) => {
      const tier = TIER_RANK[a.tier] - TIER_RANK[b.tier];
      return tier !== 0 ? tier : a.id.localeCompare(b.id);
    });

    out.push(`### ${lane} — ${laneRows.length}`, '');
    out.push('| id | name | tier | confidence | aliases |');
    out.push('|---|---|---|---|---|');
    for (const r of laneRows) {
      out.push(
        `| \`${r.id}\` | ${escapePipes(r.name)} | ${escapePipes(r.tier)} | ` +
          `${escapePipes(r.confidence)} | ${r.aliases} |`,
      );
    }
    out.push('');
  }

  return out.join('\n');
}

const doc = readFileSync(docPath, 'utf8');
const start = doc.indexOf(BEGIN);
const end = doc.indexOf(END);
if (start === -1 || end === -1) {
  console.error(`roster-ledger: ${docPath} is missing the ${BEGIN} / ${END} markers`);
  process.exit(1);
}

const updated =
  doc.slice(0, start + BEGIN.length) + '\n' + render(models()) + '\n' + doc.slice(end);

if (process.argv.includes('--check')) {
  if (updated !== doc) {
    console.error(
      'roster-ledger: Appendix A is stale — run `node scripts/roster-ledger.mjs` and commit.',
    );
    process.exit(1);
  }
  console.log('roster-ledger: Appendix A is current');
} else {
  writeFileSync(docPath, updated);
  console.log(`roster-ledger: Appendix A rewritten from ${models().length} artists`);
}
