//! What the host writes into the project file.
//!
//! This is the half of the pivot that a desktop app could not have: reopen the
//! song and the plugin comes back on the artist, seed and pins it was saved
//! with, because the DAW handed them back. The settings store it replaces was
//! per-machine and per-user; this is per-*project*, which is what a producer
//! with forty sessions actually wants.
//!
//! **The notes are not saved — the inputs that make them are.** The engine is
//! deterministic: the same model, seed and overrides produce the same pattern,
//! byte for byte, which is the property `golden.rs` and
//! `the_same_seed_reproduces_the_same_pattern_through_the_bridge` already pin
//! down. Persisting a few hundred bytes of *request* rather than a few hundred
//! kilobytes of notes means a project file stays small, and it means a pattern
//! restored next year is regenerated by the engine it is loaded with rather
//! than replayed from a format that has to stay readable forever.
//!
//! The one thing that follows from that, said out loud: **an intentional
//! engine change moves restored patterns.** That is the same trade the golden
//! snapshots already make, and the same rule applies — regenerate them, read
//! the diff, and note it in `CHANGELOG.md`.

use std::sync::{Arc, RwLock};

use engine::context::SessionOverrides;
use serde::{Deserialize, Serialize};

/// The session as the host stores it, and as the UI restores it.
///
/// Field-for-field the frontend's own session store (`src/state/session.ts`:
/// `selectedId`, `seed`, `bars`, `pins`), in `camelCase`, so the value crosses
/// the bridge without a translation layer that could disagree with either side.
///
/// **`#[serde(default)]` is load-bearing.** A project saved by an older or
/// newer build must open rather than fail: a missing field falls back to its
/// default and an unknown one is ignored. A plugin that refuses to load its own
/// state presents to a producer as a lost session with no explanation, which is
/// a far worse failure than a pin quietly reverting.
///
/// The struct therefore has a hand-written [`Default`] rather than a derived
/// one — see [`auto_sync_default`].
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", default)]
pub struct PluginSession {
    /// The selected artist, or `None` when nothing has been chosen yet.
    pub selected_id: Option<String>,
    /// The seed exactly as typed. A string because a `u64` does not survive a
    /// JSON number — the same reason `Pattern.seed` is one.
    pub seed: String,
    pub bars: Option<u16>,
    /// What the user pinned. Absent fields mean "the artist chooses", which is
    /// the distinction `SessionOverrides` exists to keep.
    ///
    /// The UI sends its four-field `SessionPins` into this six-field type and
    /// the two missing ones arrive as `None`, which is the behaviour
    /// `generate_pattern` has always relied on.
    pub pins: SessionOverrides,
    /// Which of the editor's size presets this was last left at, so a project
    /// reopens the way it was closed. `None` is the default size.
    ///
    /// A name rather than a pixel count, because the pixels depend on the
    /// display: the same project opened on a 4K desktop and a laptop should be
    /// the same *scale*, not the same number of pixels.
    pub window_size: Option<String>,
    /// Whether the tempo follows the host (TASK-P15).
    ///
    /// Part of how a song was made, so it is saved with the project like
    /// everything else here. Precedence is **user pin > (host, if this) >
    /// model**, which `crate::host::session_for` owns.
    #[serde(default = "auto_sync_default")]
    pub auto_sync: bool,
}

/// Auto-sync's default, which is **on**.
///
/// ⛔ A named function rather than `bool`'s own default, and the distinction is
/// the whole point: `#[serde(default)]` on a `bool` gives `false`, so every
/// project saved before this field existed would reopen with auto-sync *off* and
/// silently stop following its DAW. Following the host is why the plugin exists,
/// so **absent must mean on** —
/// `a_project_saved_before_auto_sync_existed_reopens_following_its_daw` is what
/// holds that.
fn auto_sync_default() -> bool {
    true
}

impl Default for PluginSession {
    fn default() -> Self {
        Self {
            selected_id: None,
            seed: String::new(),
            bars: None,
            pins: SessionOverrides::default(),
            window_size: None,
            // See `auto_sync_default`: following the host is the default because
            // it is the reason the plugin exists.
            auto_sync: true,
        }
    }
}

/// The one store, shared by the two things that need it.
///
/// It is a persisted field on [`FreallyParams`](crate::FreallyParams) *and* the
/// value the editor reads and writes, which works because `nih-plug` implements
/// `PersistentField` for `Arc<RwLock<T>>` for exactly this reason — its own
/// comment says the `Arc` wrapper exists to let persisted data be shared with
/// an editor.
///
/// **Both must be the same `Arc`.** Two stores would save one and show the
/// other, which reads as "the DAW did not save my session" and is invisible
/// until someone reopens a project.
pub type SessionStore = Arc<RwLock<PluginSession>>;

/// Read the stored session, or its default if a writer poisoned the lock.
///
/// A poisoned lock means some other thread panicked mid-write. Handing back a
/// default loses the pins; taking the panic loses the DAW. The editor is the
/// only writer and it writes a whole value at a time, so there is no torn state
/// to protect against here.
pub fn read(store: &SessionStore) -> PluginSession {
    store
        .read()
        .map(|session| session.clone())
        .unwrap_or_default()
}

/// Replace the stored session. The editor is the only caller.
pub fn write(store: &SessionStore, session: PluginSession) {
    if let Ok(mut slot) = store.write() {
        *slot = session;
    }
}

/// Change part of the stored session in place.
///
/// One lock acquisition and no clone, where read-modify-write is two of each.
/// A poisoned lock drops the change rather than the host, on the same reasoning
/// as [`read`].
pub fn update(store: &SessionStore, change: impl FnOnce(&mut PluginSession)) {
    if let Ok(mut slot) = store.write() {
        change(&mut slot);
    }
}

/// Run `f` against the stored session without copying it.
///
/// For callers that want one field: cloning the whole session to read
/// `window_size` and drop the rest is several allocations for an
/// `Option<String>`. `None` means a writer poisoned the lock, which is the same
/// condition [`read`] answers with a default — callers pick their own here
/// because "the default" is not always meaningful for a single field.
pub fn with<R>(store: &SessionStore, f: impl FnOnce(&PluginSession) -> R) -> Option<R> {
    store.read().ok().map(|session| f(&session))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_session_survives_the_round_trip_the_host_will_put_it_through() {
        // Exactly what a DAW does: serialize on save, deserialize on open.
        let session = PluginSession {
            selected_id: Some("trap".into()),
            seed: "2024".into(),
            bars: Some(8),
            pins: SessionOverrides {
                bpm: Some(150.0),
                key_root: Some(3),
                ..SessionOverrides::default()
            },
            window_size: Some("small".into()),
            auto_sync: true,
        };

        let json = serde_json::to_string(&session).unwrap();
        let back: PluginSession = serde_json::from_str(&json).unwrap();
        assert_eq!(back, session);
    }

    #[test]
    fn the_wire_names_match_the_frontends_own_field_names() {
        // The UI sends and receives this shape directly. A rename on either
        // side that is not made on the other presents as a session that saves
        // and restores as empty, with nothing reporting it.
        let json = serde_json::to_value(PluginSession {
            selected_id: Some("uk-drill".into()),
            ..PluginSession::default()
        })
        .unwrap();

        assert_eq!(json["selectedId"], "uk-drill");
        assert!(json.get("seed").is_some());
        assert!(json.get("pins").is_some());
    }

    #[test]
    fn a_project_saved_before_auto_sync_existed_reopens_following_its_daw() {
        // ⛔ The one that would have been silent. `#[serde(default)]` on a `bool`
        // gives `false`, so without `auto_sync_default` every project written
        // before TASK-P15 would come back with auto-sync *off* and quietly stop
        // following the host — which is the whole reason the plugin exists, and a
        // change nobody asked for that nothing would report.
        let old = r#"{"selectedId":"trap","seed":"7"}"#;
        let session: PluginSession = serde_json::from_str(old).unwrap();
        assert!(session.auto_sync, "absent must mean on");

        // And the default value of a fresh session agrees, so the two paths into
        // a session cannot disagree about it.
        assert!(PluginSession::default().auto_sync);

        // Off is still honoured when it is actually written.
        let off = r#"{"selectedId":"trap","autoSync":false}"#;
        let session: PluginSession = serde_json::from_str(off).unwrap();
        assert!(!session.auto_sync);
    }

    #[test]
    fn a_state_written_by_an_older_build_still_opens() {
        // The whole point of `#[serde(default)]`. A project saved before
        // `bars` and `pins` existed must reopen on its artist and seed rather
        // than refusing and losing the session.
        let old = r#"{"selectedId":"trap","seed":"7"}"#;
        let session: PluginSession = serde_json::from_str(old).unwrap();

        assert_eq!(session.selected_id.as_deref(), Some("trap"));
        assert_eq!(session.seed, "7");
        assert_eq!(session.bars, None);
        assert_eq!(session.pins, SessionOverrides::default());
    }

    #[test]
    fn the_uis_four_pins_land_in_the_engines_six_field_overrides() {
        // `SessionPins` in the frontend carries bpm/keyRoot/scale/swing;
        // `SessionOverrides` also has bars and halfTime. The two missing ones
        // must arrive as `None` — "the artist chooses" — rather than failing
        // the whole load. `generate_pattern` has always relied on this, and
        // now the saved session does too.
        let pins = r#"{"pins":{"bpm":150.0,"keyRoot":3,"scale":null,"swing":null}}"#;
        let session: PluginSession = serde_json::from_str(pins).unwrap();

        assert_eq!(session.pins.bpm, Some(150.0));
        assert_eq!(session.pins.key_root, Some(3));
        assert_eq!(session.pins.bars, None);
        assert_eq!(session.pins.half_time, None);
    }

    #[test]
    fn a_state_written_by_a_newer_build_still_opens() {
        // The other direction, which matters the moment anyone downgrades: an
        // unknown field is ignored rather than fatal.
        let newer = r#"{"selectedId":"trap","seed":"7","somethingFromTheFuture":42}"#;
        let session: PluginSession = serde_json::from_str(newer).unwrap();
        assert_eq!(session.selected_id.as_deref(), Some("trap"));
    }

    #[test]
    fn an_empty_state_is_a_fresh_session_rather_than_an_error() {
        let session: PluginSession = serde_json::from_str("{}").unwrap();
        assert_eq!(session, PluginSession::default());
        assert_eq!(session.selected_id, None);
        assert_eq!(session.seed, "");
    }

    #[test]
    fn the_store_reads_back_what_was_written() {
        let store = SessionStore::default();
        assert_eq!(read(&store), PluginSession::default());

        write(
            &store,
            PluginSession {
                selected_id: Some("plugg".into()),
                seed: "99".into(),
                ..PluginSession::default()
            },
        );

        let back = read(&store);
        assert_eq!(back.selected_id.as_deref(), Some("plugg"));
        assert_eq!(back.seed, "99");
    }
}
