//! What the host writes into the project file.
//!
//! This is the half of the pivot that a desktop app could not have: reopen the
//! song and the plugin comes back on the artist, seed and pins it was saved
//! with, because the DAW handed them back. The settings store it replaces was
//! per-machine and per-user; this is per-*project*, which is what a producer
//! with forty sessions actually wants.
//!
//! **The notes are not saved — the inputs that make them are.** The engine is
//! deterministic: the same model, seed and overrides produce the same pattern,
//! byte for byte, which is the property `golden.rs` and
//! `the_same_seed_reproduces_the_same_pattern_through_the_bridge` already pin
//! down. Persisting a few hundred bytes of *request* rather than a few hundred
//! kilobytes of notes means a project file stays small, and it means a pattern
//! restored next year is regenerated by the engine it is loaded with rather
//! than replayed from a format that has to stay readable forever.
//!
//! The one thing that follows from that, said out loud: **an intentional
//! engine change moves restored patterns.** That is the same trade the golden
//! snapshots already make, and the same rule applies — regenerate them, read
//! the diff, and note it in `CHANGELOG.md`.

use std::collections::BTreeMap;
use std::sync::{Arc, RwLock};

use engine::context::SessionOverrides;
use engine::pattern::{Lane, Part, Pattern, Song};
use serde::{Deserialize, Serialize};

/// The session as the host stores it, and as the UI restores it.
///
/// Field-for-field the frontend's own session store (`src/state/session.ts`:
/// `selectedId`, `seed`, `bars`, `pins`), in `camelCase`, so the value crosses
/// the bridge without a translation layer that could disagree with either side.
///
/// **`#[serde(default)]` is load-bearing.** A project saved by an older or
/// newer build must open rather than fail: a missing field falls back to its
/// default and an unknown one is ignored. A plugin that refuses to load its own
/// state presents to a producer as a lost session with no explanation, which is
/// a far worse failure than a pin quietly reverting.
///
/// The struct therefore has a hand-written [`Default`] rather than a derived
/// one — see [`auto_sync_default`].
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", default)]
pub struct PluginSession {
    /// The selected artist, or `None` when nothing has been chosen yet.
    pub selected_id: Option<String>,
    /// The seed exactly as typed. A string because a `u64` does not survive a
    /// JSON number — the same reason `Pattern.seed` is one.
    pub seed: String,
    /// Whether [`Self::seed`] is the producer's choice or the engine's echo.
    ///
    /// ⛔ **`Option<bool>`, and the third state is the point.** `None` means the
    /// project was written before the seed could be *unpinned* — and back then
    /// a stored seed was re-sent on every Generate, so those projects must
    /// reopen holding theirs or they stop reproducing the beat they were saved
    /// with (US-004). A plain `bool` with `#[serde(default)]` would give
    /// `false` and quietly reroll every one of them; the same trap
    /// [`auto_sync_default`] exists for, one field over.
    ///
    /// ⚠ The frontend is what resolves `None`, in `put()` — it is the side that
    /// also knows whether the seed is empty, and two answers to one question is
    /// the drift this file's header warns about.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub seed_pinned: Option<bool>,
    pub bars: Option<u16>,
    /// What the user pinned. Absent fields mean "the artist chooses", which is
    /// the distinction `SessionOverrides` exists to keep.
    ///
    /// The UI sends its four-field `SessionPins` into this six-field type and
    /// the two missing ones arrive as `None`, which is the behaviour
    /// `generate_pattern` has always relied on.
    pub pins: SessionOverrides,
    /// Which of the editor's size presets this was last left at, so a project
    /// reopens the way it was closed. `None` is the default size.
    ///
    /// A name rather than a pixel count, because the pixels depend on the
    /// display: the same project opened on a 4K desktop and a laptop should be
    /// the same *scale*, not the same number of pixels.
    pub window_size: Option<String>,
    /// Whether the tempo follows the host (TASK-P15).
    ///
    /// Part of how a song was made, so it is saved with the project like
    /// everything else here. Precedence is **user pin > (host, if this) >
    /// model**, which `crate::host::session_for` owns.
    #[serde(default = "auto_sync_default")]
    pub auto_sync: bool,
    /// The pinned mood, or `None` for "Any" (TASK-040V).
    ///
    /// ⛔ Only a *pin* is stored. "Any" is not a value to restore: the mood is
    /// then picked from the seed, so the same seed reopens on the same mood
    /// without this carrying anything — the same argument that lets the pattern
    /// itself go unsaved. Storing "Any" as a name would freeze a choice the
    /// user deliberately left open.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub mood: Option<String>,
    /// Whether the preview sampler sounds at all (FMM-S02).
    ///
    /// Part of how a song was made — a producer who silenced the plugin to
    /// route MIDI into their own drum sampler expects it silent when they
    /// reopen the project, not doubling every hit. Absent means **on**, for the
    /// same reason as [`auto_sync_default`].
    #[serde(default = "audio_enabled_default")]
    pub audio_enabled: bool,
    /// Lanes whose *audio* is muted. Their notes still reach the host.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub muted_lanes: Vec<Lane>,
    /// Lanes soloed in the preview (TASK-043). Empty means "no solo".
    ///
    /// ⛔ **Kept separate from [`Self::muted_lanes`] rather than folded into
    /// it**, and the reason is what a producer expects when they un-solo. Solo
    /// is *"everything except these, for now"* — collapsing it into the mute set
    /// would make the mutes they had chosen before soloing unrecoverable, so
    /// clicking S and clicking it again would silently rewrite their routing.
    /// The audio thread combines the two into one mask
    /// ([`crate::shared::Shared::adopt_session`]); the store keeps them apart.
    ///
    /// ⚠ Persisted like the mutes, because reopening a project should give back
    /// the state it was left in, and a solo left on with no record of it is a
    /// lane that has gone silent for no visible reason.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub soloed_lanes: Vec<Lane>,
    /// Lanes held across a reroll (TASK-044). Empty means nothing is locked.
    ///
    /// ⚠ **Stored but never read by the plugin**, and that is correct rather
    /// than an oversight: a lock decides what the *page* keeps when the engine
    /// answers, so no audio-thread state follows from it. It is here so the
    /// project reopens with the producer's locks still on — losing them would
    /// silently make the next Generate overwrite a part they had held.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub locked_lanes: Vec<Lane>,
    /// The producer's own one-shots, as **paths** to the files (TASK-131B).
    ///
    /// ⛔ **A path, not the audio, and that is a deliberate trade rather than a
    /// shortcut.** Embedding the samples would make a project file carrying five
    /// one-shots tens of megabytes, inside a `#[persist]` blob the host has to
    /// serialize on every save — and it would quietly copy somebody's sample
    /// pack into a file they may hand to someone else. Every DAW references
    /// samples by path for both reasons, and every DAW therefore has a
    /// "missing sample" state; so does this. [`crate::shared::Shared::restore_one_shots`]
    /// logs and skips a path that no longer resolves, and the lane falls back to
    /// the shipped voice rather than going silent.
    ///
    /// ⚠ **This is the exception to the module header's rule with no engine
    /// behind it.** A clip can be regenerated from its seed and a song from its
    /// artist; a sample on somebody's disk cannot be derived from anything, so
    /// there is no version of this that stores less.
    ///
    /// `BTreeMap` for the reason [`Self::patterns`] is one: a stable serialized
    /// order, so a project file does not reorder its own keys between saves.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub one_shots: BTreeMap<Lane, String>,
    /// Which of those play **backwards** (2026-08-11).
    ///
    /// ⛔⛔ **Mike:** *"'Ctrl + left arrow' when you have a sample selected should
    /// add the sample to that selected drum pad lane **in reverse**."* Reversing
    /// happens when the file is decoded, so without this a reopened project would
    /// reload the same path forwards — the producer's choice silently undone, and
    /// the kind of quiet wrong that is only noticed on playback.
    ///
    /// ⛔ **A SEPARATE MAP RATHER THAN WIDENING [`Self::one_shots`], and that is
    /// the whole reason it looks redundant.** That field is the saved project
    /// format: every existing file on Mike's disk holds `lane -> path` strings,
    /// and turning it into a struct would need a deserializer that accepts both
    /// shapes forever. An additional field defaults to empty on every old
    /// project, so nothing has to be migrated and no existing reader changes.
    ///
    /// ⚠ **Keyed by the same lane**, so an entry here without one in `one_shots`
    /// is meaningless and simply never read.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub one_shots_reversed: BTreeMap<Lane, bool>,
    /// The producer's saved sample-library folders (TASK-132).
    ///
    /// ⚠ **The same exception `one_shots` above is**: a folder on somebody's
    /// disk cannot be derived from a seed, so there is no version of this that
    /// stores less. Mike, 2026-08-07, choosing saved folders over a single
    /// picked one — a library is set up once, not once per project.
    ///
    /// ⚠ A `Vec` rather than a set, because the **order is the producer's**:
    /// they added them in the order they think about them.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub sample_folders: Vec<String>,
    /// The clips as the producer edited them, once the seed stops describing
    /// them — one per part (TASK-119).
    ///
    /// ⛔ **The exception the module header's rule needs, and only the
    /// exception.** "The notes are not saved" holds because the engine is
    /// deterministic — the seed *is* the pattern. That stops being true the
    /// moment somebody moves a note, and from then on regenerating from the
    /// seed reopens the project having silently undone their editing session.
    /// So edited clips are stored whole and unedited ones are still not stored
    /// at all: empty for every session nobody has drawn in, which is most of
    /// them, and the small-project-file property survives for those.
    ///
    /// ⚠ The trade the header names goes the other way for these: a clip saved
    /// here is *replayed*, not regenerated, so an engine improvement will not
    /// reach it. That is the right answer — the producer's edit outranks the
    /// engine's opinion of what the seed should have produced.
    ///
    /// ⚠ **A map since TASK-119, and the page can send up to five.** Before it
    /// the five generators shared one slot in the UI, so there was only ever one
    /// clip to store; now each part keeps its own. `BTreeMap` rather than
    /// `HashMap` so the serialized order is stable — a project file that
    /// reorders its own keys between saves is a diff nobody can read.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub patterns: BTreeMap<Part, Pattern>,
    /// A pre-TASK-119 project's single clip, until it has been migrated.
    ///
    /// ⛔ **This must survive a host save, and the first cut of it did not.**
    /// It was `skip_serializing` on the reasoning that a project carrying both
    /// shapes would have two answers to "what is in the drum slot" — true, but
    /// it skipped a step: **nih-plug serializes this store directly**, so a host
    /// that saves before the producer ever opens the editor rewrote the project
    /// with the legacy field dropped and `patterns` still empty. The one thing
    /// in a project file that cannot be regenerated was deleted by opening and
    /// saving.
    ///
    /// So it round-trips, and the "two answers" problem is solved by an
    /// invariant instead: **once `patterns` is non-empty this is `None`**, which
    /// [`PluginSession::migrate`] enforces on every write. There is never a
    /// moment when both hold a clip.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pattern: Option<Pattern>,
    /// Whether [`Self::patterns`] holds edits rather than the seed's own output.
    ///
    /// Carried explicitly rather than inferred from the map being non-empty,
    /// because the UI has to know on restore whether to trust the stored clips
    /// or press on with the seed — and "there happen to be patterns here" does
    /// not answer that.
    #[serde(default)]
    pub edited: bool,
    /// The arrangement, once the producer has edited it away from its seed
    /// (TASK-067).
    ///
    /// ⛔ **The same rule as [`Self::pattern`], one document up, and it is the
    /// rule rather than a second policy.** A song is derived from the artist,
    /// the seed and the pins exactly as a pattern is, so an *unedited* one is
    /// reproducible by pressing Generate and is not worth a byte in the project
    /// file. The moment a section is resized, cloned, deleted or re-rolled, the
    /// seed stops describing what is on screen — and from then on reopening the
    /// project without this would hand the producer the song they started from,
    /// having silently thrown away the arrangement they built.
    ///
    /// ⚠ A song is much larger than a clip: it carries a pattern per part per
    /// distinct section. That is the cost of the edit being real, and it is only
    /// paid by projects that have one.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub song: Option<Song>,
    /// Whether [`Self::song`] is an arrangement rather than the seed's own
    /// output — the same explicit flag, for the same reason, as
    /// [`Self::edited`].
    #[serde(default)]
    pub song_edited: bool,
}

/// The preview sampler's default, which is **on**.
///
/// ⛔ Safe to default this way because **no build has ever shipped**: no saved
/// project predates the sampler, so none can be surprised by it. A generator
/// nobody can hear without wiring an instrument up first is the problem the
/// sampler exists to fix.
fn audio_enabled_default() -> bool {
    true
}

/// Auto-sync's default, which is **on**.
///
/// ⛔ A named function rather than `bool`'s own default, and the distinction is
/// the whole point: `#[serde(default)]` on a `bool` gives `false`, so every
/// project saved before this field existed would reopen with auto-sync *off* and
/// silently stop following its DAW. Following the host is why the plugin exists,
/// so **absent must mean on** —
/// `a_project_saved_before_auto_sync_existed_reopens_following_its_daw` is what
/// holds that.
fn auto_sync_default() -> bool {
    true
}

impl PluginSession {
    /// Fold a pre-TASK-119 single clip into [`Self::patterns`], once.
    ///
    /// ⛔ **The invariant this exists to hold: `pattern` and `patterns` are
    /// never both populated.** The legacy field has to round-trip a host save,
    /// because nih-plug may serialize this store before the editor has ever
    /// opened — but two live copies of "the drum slot" with no rule for which
    /// wins is the drift the first cut of this was trying to avoid. Folding on
    /// every write gives both properties.
    ///
    /// The clip names its own `part`, so nothing is guessed. A legacy clip
    /// arriving *beside* a populated map is dropped rather than merged: the map
    /// is the newer shape, and a project that somehow carried both has already
    /// been through a build that wrote the map.
    pub fn migrate(&mut self) {
        let Some(clip) = self.pattern.take() else {
            return;
        };
        if self.patterns.is_empty() {
            self.patterns.insert(clip.part, clip);
        }
    }
}

impl Default for PluginSession {
    fn default() -> Self {
        Self {
            selected_id: None,
            seed: String::new(),
            // Nothing stored says nothing was chosen. See the field's own note
            // for why this is `None` rather than `Some(false)`.
            seed_pinned: None,
            bars: None,
            pins: SessionOverrides::default(),
            window_size: None,
            // See `auto_sync_default`: following the host is the default because
            // it is the reason the plugin exists.
            auto_sync: true,
            mood: None,
            audio_enabled: true,
            muted_lanes: Vec::new(),
            soloed_lanes: Vec::new(),
            locked_lanes: Vec::new(),
            one_shots: BTreeMap::new(),
            one_shots_reversed: BTreeMap::new(),
            sample_folders: Vec::new(),
            patterns: BTreeMap::new(),
            pattern: None,
            edited: false,
            song: None,
            song_edited: false,
        }
    }
}

/// The one store, shared by the two things that need it.
///
/// It is a persisted field on [`FreallyParams`](crate::FreallyParams) *and* the
/// value the editor reads and writes, which works because `nih-plug` implements
/// `PersistentField` for `Arc<RwLock<T>>` for exactly this reason — its own
/// comment says the `Arc` wrapper exists to let persisted data be shared with
/// an editor.
///
/// **Both must be the same `Arc`.** Two stores would save one and show the
/// other, which reads as "the DAW did not save my session" and is invisible
/// until someone reopens a project.
pub type SessionStore = Arc<RwLock<PluginSession>>;

/// Read the stored session, or its default if a writer poisoned the lock.
///
/// A poisoned lock means some other thread panicked mid-write. Handing back a
/// default loses the pins; taking the panic loses the DAW. The editor is the
/// only writer and it writes a whole value at a time, so there is no torn state
/// to protect against here.
pub fn read(store: &SessionStore) -> PluginSession {
    store
        .read()
        .map(|session| session.clone())
        .unwrap_or_default()
}

/// Replace the stored session. The editor is the only caller.
pub fn write(store: &SessionStore, mut session: PluginSession) {
    session.migrate();
    if let Ok(mut slot) = store.write() {
        *slot = session;
    }
}

/// Change part of the stored session in place.
///
/// One lock acquisition and no clone, where read-modify-write is two of each.
/// A poisoned lock drops the change rather than the host, on the same reasoning
/// as [`read`].
pub fn update(store: &SessionStore, change: impl FnOnce(&mut PluginSession)) {
    if let Ok(mut slot) = store.write() {
        change(&mut slot);
    }
}

/// Run `f` against the stored session without copying it.
///
/// For callers that want one field: cloning the whole session to read
/// `window_size` and drop the rest is several allocations for an
/// `Option<String>`. `None` means a writer poisoned the lock, which is the same
/// condition [`read`] answers with a default — callers pick their own here
/// because "the default" is not always meaningful for a single field.
pub fn with<R>(store: &SessionStore, f: impl FnOnce(&PluginSession) -> R) -> Option<R> {
    store.read().ok().map(|session| f(&session))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// One edited melody clip — the shape a producer's hand-edit takes.
    fn sample_clip() -> Pattern {
        Pattern {
            id: "trap-7".into(),
            part: Part::Melody,
            artist_id: "trap".into(),
            seed: 7,
            song_seed: 7,
            bars: 4,
            bpm: 140.0,
            time_sig_num: 4,
            time_sig_den: 4,
            key_root: 6,
            scale: engine::pattern::Scale::NaturalMinor,
            lanes: vec![engine::pattern::LaneTrack {
                lane: Lane::Melody,
                notes: vec![engine::pattern::Note {
                    start_tick: 480,
                    len_ticks: 240,
                    pitch: 61,
                    vel: 99,
                    model_vel: Some(84),
                    slide_to_pitch: None,
                    articulation: None,
                    reversed: false,
                }],
            }],
            ppq: engine::pattern::PPQ,
            mood: None,
            loop_region: Some(engine::pattern::Region {
                from_tick: 0,
                to_tick: 3840,
            }),
            clip_region: None,
        }
    }

    #[test]
    fn a_session_survives_the_round_trip_the_host_will_put_it_through() {
        // Exactly what a DAW does: serialize on save, deserialize on open.
        let session = PluginSession {
            selected_id: Some("trap".into()),
            seed: "2024".into(),
            seed_pinned: Some(true),
            bars: Some(8),
            pins: SessionOverrides {
                bpm: Some(150.0),
                key_root: Some(3),
                ..SessionOverrides::default()
            },
            window_size: Some("small".into()),
            auto_sync: true,
            mood: Some("dark".into()),
            audio_enabled: false,
            muted_lanes: vec![Lane::Snare],
            soloed_lanes: vec![Lane::Kick],
            locked_lanes: vec![Lane::ClosedHat],
            one_shots: BTreeMap::from([(Lane::Melody, "C:/samples/lead.wav".to_owned())]),
            // ⚠ Reversed too, so the round trip proves the new field survives
            // a save and an open rather than only the old one.
            one_shots_reversed: BTreeMap::from([(Lane::Melody, true)]),
            // The sample library rides with the project too (TASK-132).
            sample_folders: vec!["C:/samples".to_owned()],
            patterns: BTreeMap::new(),
            pattern: None,
            edited: false,
            song: None,
            song_edited: false,
        };

        let json = serde_json::to_string(&session).unwrap();
        let back: PluginSession = serde_json::from_str(&json).unwrap();
        assert_eq!(back, session);
    }

    #[test]
    fn an_edited_clip_survives_the_round_trip_whole() {
        // ⛔ TASK-041's own gate. Everything else here is saved as the *inputs*
        // that regenerate it, because the engine is deterministic — and the
        // moment a producer moves a note that stops being true. A clip that did
        // not survive this would reopen the project having silently undone
        // their editing session, with the seed as the only explanation.
        let mut edited = PluginSession {
            selected_id: Some("trap".into()),
            seed: "7".into(),
            ..PluginSession::default()
        };
        let clip = sample_clip();
        edited.patterns = BTreeMap::from([(Part::Melody, clip.clone())]);
        edited.edited = true;

        let json = serde_json::to_string(&edited).unwrap();
        let back: PluginSession = serde_json::from_str(&json).unwrap();
        assert_eq!(back, edited, "the clip, its loop and its model velocities");

        // And an unedited session still carries no notes at all, which is the
        // property that keeps a project file a few hundred bytes.
        let plain = PluginSession::default();
        let json = serde_json::to_string(&plain).unwrap();
        assert!(
            !json.contains("pattern"),
            "an unedited session must not store a clip: {json}"
        );
    }

    #[test]
    fn a_project_saved_before_the_five_slots_still_opens_with_its_clip() {
        // ⛔ TASK-119 turned one clip into five, and a producer's saved edit is
        // the one thing in a project file that cannot be regenerated. A build
        // that dropped it would present as "reopening lost my editing session",
        // which is the exact failure `an_edited_clip_survives_the_round_trip`
        // exists to prevent — arriving through the upgrade instead.
        let legacy = r#"{
            "selectedId": "trap",
            "seed": "7",
            "edited": true,
            "pattern": {
                "id": "trap-7", "part": "melody", "artistId": "trap", "seed": 7,
                "bars": 4, "bpm": 140.0, "timeSigNum": 4, "timeSigDen": 4,
                "keyRoot": 6, "scale": "natural_minor", "lanes": [], "ppq": 960
            }
        }"#;

        let opened: PluginSession = serde_json::from_str(legacy).unwrap();
        let carried = opened.pattern.as_ref().expect("the legacy clip must load");
        assert_eq!(carried.part, Part::Melody);
        assert!(opened.edited);
        // The page migrates it into the map by the clip's own `part`; nothing
        // here guesses, which is why the field is carried rather than converted.
        assert!(opened.patterns.is_empty());

        // ⛔ **And it survives a host save that happens before the editor has
        // ever opened.** This assertion used to say the opposite, and the
        // opposite was a defect: nih-plug serializes this store directly, so a
        // project opened and saved without the producer touching the window was
        // rewritten with the clip dropped and `patterns` still empty — deleting
        // the one thing in a project file that cannot be regenerated.
        let rewritten = serde_json::to_string(&opened).unwrap();
        assert!(
            rewritten.contains("\"pattern\":"),
            "the legacy clip must round-trip until it is migrated: {rewritten}"
        );

        // ⛔ **And the two shapes are never both populated.** `migrate` runs on
        // every `write`, folding the clip into the map by its own `part`, so
        // there is no moment where "what is in the melody slot" has two answers.
        let mut migrated = opened.clone();
        migrated.migrate();
        assert!(
            migrated.pattern.is_none(),
            "the legacy field must be cleared"
        );
        assert_eq!(
            migrated.patterns.get(&Part::Melody).map(|p| p.id.as_str()),
            Some("trap-7"),
            "the clip must land in the slot its own `part` names"
        );

        let after = serde_json::to_string(&migrated).unwrap();
        assert!(
            !after.contains("\"pattern\":"),
            "once migrated the legacy field must not be written again: {after}"
        );
    }

    #[test]
    fn writing_a_session_migrates_a_legacy_clip_rather_than_leaving_two_copies() {
        // `write` is the path every save from the editor takes, which is where
        // the invariant has to be enforced — a caller that had to remember to
        // call `migrate` is a caller that will forget.
        let store = SessionStore::default();
        let mut legacy = PluginSession {
            edited: true,
            ..PluginSession::default()
        };
        legacy.pattern = Some(sample_clip());

        write(&store, legacy);

        let stored = read(&store);
        assert!(stored.pattern.is_none());
        assert_eq!(stored.patterns.len(), 1);
        assert!(stored.patterns.contains_key(&Part::Melody));
    }

    /// The smallest thing that is recognisably an arrangement: one section
    /// playing one clip, out of a store that holds it.
    fn sample_song() -> Song {
        use engine::pattern::{PatternRef, Section, SectionKind};
        use std::collections::BTreeMap;

        let clip = Pattern {
            id: "trap-hook-drums".into(),
            part: engine::pattern::Part::Drums,
            artist_id: "trap".into(),
            seed: 9,
            song_seed: 9,
            bars: 4,
            bpm: 140.0,
            time_sig_num: 4,
            time_sig_den: 4,
            key_root: 0,
            scale: engine::pattern::Scale::NaturalMinor,
            lanes: vec![engine::pattern::LaneTrack {
                lane: Lane::Kick,
                notes: vec![engine::pattern::Note {
                    start_tick: 0,
                    len_ticks: 120,
                    pitch: 36,
                    vel: 110,
                    model_vel: None,
                    slide_to_pitch: None,
                    articulation: None,
                    reversed: false,
                }],
            }],
            ppq: engine::pattern::PPQ,
            mood: None,
            loop_region: None,
            clip_region: None,
        };
        Song {
            id: "trap-song-9".into(),
            artist_id: "trap".into(),
            seed: 9,
            bpm: 140.0,
            key_root: 0,
            scale: engine::pattern::Scale::NaturalMinor,
            sections: vec![Section {
                kind: SectionKind::Hook,
                start_bar: 0,
                bars: 8,
                patterns: BTreeMap::from([(
                    engine::pattern::Part::Drums,
                    PatternRef {
                        pattern_id: "trap-hook-drums".into(),
                        bars: None,
                    },
                )]),
                drop_out_beats: 0,
                decay: false,
                markers: vec![],
            }],
            time_sig_num: 4,
            time_sig_den: 4,
            patterns: BTreeMap::from([("trap-hook-drums".to_owned(), clip)]),
            ppq: engine::pattern::PPQ,
        }
    }

    #[test]
    fn an_edited_arrangement_survives_the_round_trip_whole() {
        // ⛔ TASK-067's own gate, and the failure it closes is the one three
        // handoffs have written down: arranging a whole song and reopening the
        // project lost every bit of it, while a single edited *pattern*
        // survived. `useSong.edited` existed and nothing read it.
        let mut edited = PluginSession {
            selected_id: Some("trap".into()),
            seed: "9".into(),
            ..PluginSession::default()
        };
        edited.song = Some(sample_song());
        edited.song_edited = true;

        let json = serde_json::to_string(&edited).unwrap();
        let back: PluginSession = serde_json::from_str(&json).unwrap();
        assert_eq!(back, edited, "the arrangement, its sections and its clips");

        // And an *unedited* session still carries no arrangement, which is what
        // keeps a project file a few hundred bytes for the sessions — most of
        // them — that never opened Song Mode.
        let plain = PluginSession::default();
        let json = serde_json::to_string(&plain).unwrap();
        assert!(
            !json.contains("\"song\""),
            "an unedited session must not store an arrangement: {json}"
        );
    }

    #[test]
    fn assigned_one_shots_survive_the_round_trip_and_an_unassigned_project_stores_none() {
        // ⛔ TASK-131B's own gate. A sample on somebody's disk is the one thing
        // in this struct that cannot be derived from anything — there is no
        // seed that regenerates it — so losing it on a reopen loses the kit the
        // producer built, with nothing to explain where it went.
        let assigned = PluginSession {
            selected_id: Some("trap".into()),
            one_shots: BTreeMap::from([
                (Lane::Melody, "C:/samples/leads/glass.wav".to_owned()),
                (Lane::Kick, "/home/mike/kicks/808 kick.aiff".to_owned()),
            ]),
            ..PluginSession::default()
        };

        let json = serde_json::to_string(&assigned).unwrap();
        let back: PluginSession = serde_json::from_str(&json).unwrap();
        assert_eq!(back, assigned, "every path, keyed by its lane");

        // Serialized by lane *name*, so reordering the enum cannot remap a
        // saved project onto a different pad — the same property
        // `muted_lanes` relies on.
        assert!(json.contains("\"melody\""), "{json}");

        // And a project nobody assigned anything in carries no key at all,
        // which is what keeps an ordinary session a few hundred bytes.
        let plain = serde_json::to_string(&PluginSession::default()).unwrap();
        assert!(
            !plain.contains("oneShots"),
            "an unassigned session must store nothing: {plain}"
        );
    }

    #[test]
    fn a_project_saved_before_one_shots_existed_still_opens() {
        // The `#[serde(default)]` rule applied to the new field, which is the
        // rule this struct's header calls load-bearing.
        let old = r#"{"selectedId":"trap","seed":"7","edited":true}"#;
        let session: PluginSession = serde_json::from_str(old).unwrap();

        assert_eq!(session.selected_id.as_deref(), Some("trap"));
        assert!(session.one_shots.is_empty());
    }

    #[test]
    fn a_project_saved_before_song_mode_existed_still_opens() {
        // The `#[serde(default)]` rule applied to the two new fields. A project
        // written before this shipped must reopen on its artist and seed rather
        // than refusing, which presents to a producer as a lost session.
        let old = r#"{"selectedId":"trap","seed":"7","edited":true}"#;
        let session: PluginSession = serde_json::from_str(old).unwrap();

        assert_eq!(session.selected_id.as_deref(), Some("trap"));
        assert_eq!(session.song, None);
        assert!(!session.song_edited);
    }

    #[test]
    fn the_wire_names_match_the_frontends_own_field_names() {
        // The UI sends and receives this shape directly. A rename on either
        // side that is not made on the other presents as a session that saves
        // and restores as empty, with nothing reporting it.
        let json = serde_json::to_value(PluginSession {
            selected_id: Some("uk-drill".into()),
            // ⚠ Set, because the field is skipped when `None` — a default
            // session would prove nothing about its name.
            seed_pinned: Some(true),
            ..PluginSession::default()
        })
        .unwrap();

        assert_eq!(json["selectedId"], "uk-drill");
        assert!(json.get("seed").is_some());
        assert!(json.get("pins").is_some());
        // ⛔ `seedPinned`, not `seed_pinned`. The frontend reads this key by
        // name in `put()`, and a mismatch presents as a seed that silently
        // stops being held — which is the defect it was added to close.
        assert_eq!(json["seedPinned"], true);
    }

    #[test]
    fn a_project_saved_before_auto_sync_existed_reopens_following_its_daw() {
        // ⛔ The one that would have been silent. `#[serde(default)]` on a `bool`
        // gives `false`, so without `auto_sync_default` every project written
        // before TASK-P15 would come back with auto-sync *off* and quietly stop
        // following the host — which is the whole reason the plugin exists, and a
        // change nobody asked for that nothing would report.
        let old = r#"{"selectedId":"trap","seed":"7"}"#;
        let session: PluginSession = serde_json::from_str(old).unwrap();
        assert!(session.auto_sync, "absent must mean on");

        // And the default value of a fresh session agrees, so the two paths into
        // a session cannot disagree about it.
        assert!(PluginSession::default().auto_sync);

        // Off is still honoured when it is actually written.
        let off = r#"{"selectedId":"trap","autoSync":false}"#;
        let session: PluginSession = serde_json::from_str(off).unwrap();
        assert!(!session.auto_sync);
    }

    #[test]
    fn a_state_written_by_an_older_build_still_opens() {
        // The whole point of `#[serde(default)]`. A project saved before
        // `bars` and `pins` existed must reopen on its artist and seed rather
        // than refusing and losing the session.
        let old = r#"{"selectedId":"trap","seed":"7"}"#;
        let session: PluginSession = serde_json::from_str(old).unwrap();

        assert_eq!(session.selected_id.as_deref(), Some("trap"));
        assert_eq!(session.seed, "7");
        assert_eq!(session.bars, None);
        assert_eq!(session.pins, SessionOverrides::default());
    }

    #[test]
    fn the_uis_four_pins_land_in_the_engines_six_field_overrides() {
        // `SessionPins` in the frontend carries bpm/keyRoot/scale/swing;
        // `SessionOverrides` also has bars and halfTime. The two missing ones
        // must arrive as `None` — "the artist chooses" — rather than failing
        // the whole load. `generate_pattern` has always relied on this, and
        // now the saved session does too.
        let pins = r#"{"pins":{"bpm":150.0,"keyRoot":3,"scale":null,"swing":null}}"#;
        let session: PluginSession = serde_json::from_str(pins).unwrap();

        assert_eq!(session.pins.bpm, Some(150.0));
        assert_eq!(session.pins.key_root, Some(3));
        assert_eq!(session.pins.bars, None);
        assert_eq!(session.pins.half_time, None);
    }

    #[test]
    fn a_state_written_by_a_newer_build_still_opens() {
        // The other direction, which matters the moment anyone downgrades: an
        // unknown field is ignored rather than fatal.
        let newer = r#"{"selectedId":"trap","seed":"7","somethingFromTheFuture":42}"#;
        let session: PluginSession = serde_json::from_str(newer).unwrap();
        assert_eq!(session.selected_id.as_deref(), Some("trap"));
    }

    /// A project saved before the seed could be *unpinned* must not start
    /// rolling one (2026-08-06).
    ///
    /// ⛔ **The `Option` is the whole point, and a `bool` here would be silently
    /// wrong.** `#[serde(default)]` on a `bool` gives `false`, which the
    /// frontend reads as "the producer never chose this seed" and answers by
    /// asking the engine for a new one — so every project anybody had already
    /// saved would reopen generating a different beat. `None` is the third
    /// state that lets `put()` tell "unpinned" from "written before the
    /// question existed", the same trap `auto_sync_default` exists for.
    #[test]
    fn a_project_saved_before_the_seed_pin_existed_does_not_claim_to_be_unpinned() {
        let old = r#"{"selectedId":"trap","seed":"7"}"#;
        let session: PluginSession = serde_json::from_str(old).unwrap();

        assert_eq!(session.seed, "7");
        assert_eq!(
            session.seed_pinned, None,
            "an absent pin was read as a deliberate `false`, which rerolls every saved project"
        );
    }

    #[test]
    fn an_unpinned_seed_survives_the_round_trip_as_itself() {
        // The other direction: a session that really did leave the seed to the
        // engine must reopen that way, not be re-pinned by the fallback above.
        let session = PluginSession {
            seed: "7".into(),
            seed_pinned: Some(false),
            ..PluginSession::default()
        };
        let json = serde_json::to_string(&session).unwrap();
        let back: PluginSession = serde_json::from_str(&json).unwrap();

        assert_eq!(back.seed_pinned, Some(false));
    }

    #[test]
    fn an_empty_state_is_a_fresh_session_rather_than_an_error() {
        let session: PluginSession = serde_json::from_str("{}").unwrap();
        assert_eq!(session, PluginSession::default());
        assert_eq!(session.selected_id, None);
        assert_eq!(session.seed, "");
    }

    #[test]
    fn the_store_reads_back_what_was_written() {
        let store = SessionStore::default();
        assert_eq!(read(&store), PluginSession::default());

        write(
            &store,
            PluginSession {
                selected_id: Some("plugg".into()),
                seed: "99".into(),
                ..PluginSession::default()
            },
        );

        let back = read(&store);
        assert_eq!(back.selected_id.as_deref(), Some("plugg"));
        assert_eq!(back.seed, "99");
    }
}
